### ISSUE TITLE
setup.sh -> Cloning into 'procgen'... ERROR: Repository not found.

### ISSUE THREAD

**Issue by maciekpoplawski** [princeton-vl/infinigen#1]
![image](https://github.com/princeton-vl/infinigen/assets/54249329/2501bce7-ecc3-4f2a-b051-eec3d52f9be4)
:(

[infinigen](https://github.com/princeton-vl/infinigen/tree/main)/[docker](https://github.com/princeton-vl/infinigen/tree/main/docker)/setup.sh 
at line 2

**Comment by maciekpoplawski** [comment]
but but! cloning repo directly inside docker container and running demo got me this!
![image](https://github.com/princeton-vl/infinigen/assets/54249329/88e653c4-59ef-4a8d-8214-71b635a1352b)

![image](https://github.com/princeton-vl/infinigen/assets/54249329/658ff5a3-d6eb-4b59-892f-0f2594e4a298)

**Comment by David-Yan1** [comment]
In `/docker/setup.sh`, replace `git@github.com:princeton-vl/procgen.git` with `https://github.com/princeton-vl/infinigen.git`. Then rerun `bash make_docker.sh`

This will be fixed soon in an upcoming patch.

**Comment by David-Yan1** [comment]
For others reading this thread, the fixed setup.sh script should look like this

```
eval `ssh-agent -s` && ssh-add ~/.ssh/id_ed25519
git clone --recursive https://github.com/princeton-vl/infinigen.git
conda init bash && . ~/.bashrc
cd infinigen
conda create --name infinigen python=3.10 -y
conda activate procgen && bash install.sh
```
