### ISSUE TITLE
infinigen/blender/generate.py" could not be opened: No such file or directory

### ISSUE THREAD

**Issue by mischaschaub** [princeton-vl/infinigen#10]
BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read prefs: /home/mischa/.config/blender/3.3/config/userpref.blend
/mnt/wslg/runtime-dir/gvfs/ non-existent directory
Error: Python: OSError: Python file "/mnt/c/Users/mischa/infinigen/blender/generate.py" could not be opened: No such file or directory

Any idea what might be wrong here? Still trying to get this lovely approach to run on WSL on a 3090, please help

**Comment by araistrick** [comment]
Please make sure you are executing all commands from inside the infinigen/worldgen working directory, as specified by the 'cd worldgen' command

**Comment by Jamamuuga** [comment]
The directions in the read me need to be updated to reflect this...
