### ISSUE TITLE
could not export .blend to .fbx 

### ISSUE THREAD

**Issue by chongxian** [princeton-vl/infinigen#101]
I have an issue about /worldgen/tools/export/export.py , when I try to export scene.blend to .fbx, it may export some .png and report segmentation fault, never export .fbx file.  And I try to export small .blend file to .fbx file, such as a scene.blend only had a TreeFactory,but also does not work. Thanks for your help.
![image](https://github.com/princeton-vl/infinigen/assets/18145013/6d58c1ec-552c-401d-a2b7-299c8bd3198f)
when I export the tree only get texture and can't get geometry
![image](https://github.com/princeton-vl/infinigen/assets/18145013/1bbf6ac1-a07d-4ef3-8847-81793265d1d5)

**Comment by dongyh20** [comment]
I'm also trying to export a mesh and got the same problem. But could you please show me how to get a scene.blend only had a TreeFactory? I also want to do this.

**Comment by David-Yan1** [comment]
Could both of you post the full standard output of the export script? I suspect that this may be an out of memory issue though  - trees are quite difficult to export because of their complexity.

**Comment by chongxian** [comment]
> 
when I export the tree, if I not unhide the Tree.001, Tree.002,Tree.003 from render，It can't export  anything.
![image](https://github.com/princeton-vl/infinigen/assets/18145013/3fe0e5ed-6528-4a54-94e7-cb803617f32b)
![image](https://github.com/princeton-vl/infinigen/assets/18145013/6b6826ca-37d4-4a79-b537-6009c9d8a0c1)

And if I unhide the Tree from render, it will export some texture but also not export .fbx,
![image](https://github.com/princeton-vl/infinigen/assets/18145013/b6e4c2e8-1a68-4319-803f-562845825224)

**Comment by dongyh20** [comment]
Currently I can only export a tree without leaves, I guess the spawn_asset in .blend is not exported correctly

**Comment by dongyh20** [comment]
When I use the provided export.py, I got the same output as above.

**Comment by David-Yan1** [comment]
As to

> I'm also trying to export a mesh and got the same problem. But could you please show me how to get a scene.blend only had a TreeFactory? I also want to do this.

You can use `asset_grid.py` to generate singular asset blend files. More comprehensive instructions on how to use it coming in a future release.
