### ISSUE TITLE
how to use the generated_surface_scripts.py?

### ISSUE THREAD

**Issue by chongxian** [princeton-vl/infinigen#103]
Hello, I have an problem about the node_transpiler，when I create a blend file only include geometry node, and I use the dev_script.py to convert node-graphs to python code, but noly get the  generated_surface_scripts.py file. how to use the  generated_surface_scripts.py and get some information like Figure.3 in your paper(eg. has some parameters like desinty?), could your kindly to teach me? 
![image](https://github.com/princeton-vl/infinigen/assets/18145013/121f2a76-fb56-4101-84e2-cf9462223e3c)
![image](https://github.com/princeton-vl/infinigen/assets/18145013/d672531a-3a53-4a49-b370-7aede19b32e8)

**Comment by araistrick** [comment]
Hello,

To get randomized values included in the Python code, you can give any Value node an annotated name like 'Density ~ U(5,20)' and a corresponding np.random call should appear in the Python. It won't be quite the format shown - the code in the figure is somewhat compacted and illustrative.

If you want to run the genwrated_surface_script.py, just open it up in the blender scripting panel, select some object (like the default cube etc) to apply the geonodes ontop of, then click play to run the script in the UI. Or, you can look at some of our code examples like flower.py or simple_greenery.py to see what it looks like running headless

**Comment by chongxian** [comment]
Thanks for your reply ,but I use the wsl don't have the UI,  how can I do to use the generate_surface_script.py？I use the command "$BLENDER -b empty.blend --python generated_surface_script.py " and  export warning:  File written by newer Blender binary (305.8), expect loss of data!
