### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JnkDesign** [princeton-vl/infinigen#104]
**Describe the bug**
cant launch commands tried on 3 PCs.... 

command not found

BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse 
**Steps to Reproduce**
- What version of the code were you using? Tell us the output of `git log -n 1`
'''
$ git log -n 1
...
'''

- What command did you run?
```
Add your command here
``` $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse

command not found


- What are your output logs? 
```
Add your logs here, preferably from a job run with --debug 
```

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**


```
Add your install.sh logs here
```

**Platform**
- OS & OS Version:  lts 22 
- GPU (?) : quadro 5000 
- GPU Driver Version (?) : 535
- RAM (GB): 10 

**Additional context**
Add any other context about the problem here.

**Comment by andzejsp** [comment]
use $ in front of BLENDER

**Comment by JnkDesign** [comment]
i did : $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse

command not found

**Comment by tmhedesign** [comment]
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
![Screenshot 2023-07-21 133623](https://github.com/princeton-vl/infinigen/assets/117762518/0f5af5e1-be30-4691-b2c3-9984790cd78e)

**Comment by tmhedesign** [comment]
![Screenshot 2023-07-21 134449](https://github.com/princeton-vl/infinigen/assets/117762518/8e608382-f705-44a6-b7b8-b5b3ba6a6df2)

**Comment by andzejsp** [comment]
did the blender even download? looks like it did not.

On the first time you used bash install.sh did it download blender? there should be infinigen/blender folder

**Comment by tmhedesign** [comment]
> did the blender even download? looks like it did not.
> 
> On the first time you used bash install.sh did it download blender? there should be infinigen/blender folder

Yes 
![Uploading Screenshot 2023-07-21 142454.png…]()

**Comment by andzejsp** [comment]
guy, why u no follow instructions?

smelly

it says
```
export BLENDER="/PATH/TO/infinigen/blender/blender"
```

after that the $BLENDER will work..

**Comment by araistrick** [comment]
Hello, thanks for posting, I think #51 may help.
