### ISSUE TITLE
scatter: BlenderRockFactory has no vertices.

### ISSUE THREAD

**Issue by Inshsang** [princeton-vl/infinigen#108]
**Describe the feature you would like to see implemented**
Scatter: BlenderRockFactory has no vertices. It cannot be exported, but it will be rendered in the image. Is there a way to export Scatter: BlenderRockFactory as a PLY file?

**Comment by Inshsang** [comment]
polycounts.txt in 'fine' include
animhelper: 0
assets: 80,752
assets:BlenderRockFactory(27855): 62
assets:BushFactory(36234574).twigs: 39,046
assets:BushFactory(543568399).twigs: 34,070
assets:GenericTreeFactory(60608): 7,574
assets:TreeFlowerFactory(36234574): 0
assets:TreeFlowerFactory(543568399): 0
CameraRigs: 0
Collection: 335,768
colliders: 7,060
particleassets: 0
particles: 0
placeholders: 78
placeholders:BushFactory(36234574): 30
placeholders:BushFactory(543568399): 24
placeholders:CactusFactory(1375975078): 6
placeholders:CactusFactory(36234574): 18
placeholders:CactusFactory(543568399): 0
scatter: 0
scatters: 0
terrain: 2,480,133
unique_assets: 2,630,663
unique_assets:BushFactory(36234574): 0
unique_assets:BushFactory(543568399): 2,060
unique_assets:CactusFactory(1375975078): 629,296
unique_assets:CactusFactory(36234574): 1,999,307
unique_assets:CactusFactory(543568399): 0
Faces:2,547,659Tris:2,973,680Objects:0/50Memory: 698.9 MiB3.3.1

**Comment by chuong** [comment]
@araistrick Could please point to the savemesh solution by @lahavlipson? I could not find it anywhere.

**Comment by araistrick** [comment]
@chuong if you run manage_datagen_jobs with the opengl_gt.gin config, a step will run named 'save_mesh' which executes core.py's `save_meshes` function and dumps many npy files to `output_folder/seed/savemeshXXXX`
