### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by maciekpoplawski** [princeton-vl/infinigen#11]
I would like to know if there are some special steps needed to be able to use GPU power when using infinigen? I tried WSL2 Ubuntu 20.04 and Docker but botch cases it only uses CPU + says no Optix available due to non available device with ability to run Optix. 
BTW nvidia-smi shows proper card + drivers.
![image](https://github.com/princeton-vl/infinigen/assets/54249329/5c50a654-81f8-4ab9-9db0-ecf1520f13b8)

System: 
Windows 10
RTX 3090 latest drivers
WSL2 Ubunu 20.04 installed from provided tutorial from Readme
latest Docker for Windows

**Comment by David-Yan1** [comment]
We are working on getting more formal instructions out for Windows WSL soon, but in the meantime make sure that you have followed these steps. 

- Follow the instructions [here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl-2) to install CUDA on WSL2. This is probably the most important and likely error.

- Make sure that you have [installed](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview) WSL 2 (with WSLg) and Ubuntu. Make sure that you are either on the latest version of Windows 10 or on Windows 11.   It seems you've already done this, but check that GUI programs are working in WSL like gedit or xeyes.

- In Powershell, run wsl -l -v to verify that WSL is using version 2. If not, refer to [this](https://learn.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2.) guide on upgrading.

- Verify that echo $DISPLAY in WSL returns :0. If not, WSLg was not properly set up. If you had previous installations of WSL/Ubuntu, try uninstalling and doing a fresh install of both.

Then rerun `bash install.sh` and make sure that you use `--pipeline_configs enable_gpu` when doing generation. Keep in mind that only terrain generation is GPU-accelerated.
