### ISSUE TITLE
[REQUEST] how to streamline the configurations?

### ISSUE THREAD

**Issue by wi11Iam5-mpu** [princeton-vl/infinigen#111]
**Describe the feature you would like to see implemented**

Thank you for your work. I find that the time cost of data generation is too high in my case. Can I save time by giving a minimized configuration such as only one creature and a small terrain area.

**Comment by way2coder** [comment]
Also need a solution for this problem, for some cases I just want a generation for trees or creatures.

**Comment by araistrick** [comment]
Hello! thanks for the question, we have just published some settings to try out as part of our [`Configuring Infinigen`](docs/ConfiguringInfinigen.md) docs, as part of v1.0.2 #115.

Hopefully these are helpful. We will continue to work on making Infinigen more efficient and accessible.
