### ISSUE TITLE
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by UnitySe3D** [princeton-vl/infinigen#112]
when I the code tries to import bpy it gives this error: ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

I am on WSL

**Comment by araistrick** [comment]
Hello, I believe you may need to apt-get some extra dependencies as discussed in #28. Apologies these are not specified in the install instructions, on our platform(s) they were included by default and/or installed by blender. I will make an internal ticket to provide a full list of apt-get dependencies.
