### ISSUE TITLE
[REQUEST]Export the entire scene at an extremely low resolution

### ISSUE THREAD

**Issue by Inshsang** [princeton-vl/infinigen#117]
**Describe the feature you would like to see implemented**

Hello，I am interested in obtaining a rich point cloud dataset of objects, and I am wondering if it is feasible. I would like to inquire if there are any methods to fully instantiate the visible scene with an acceptable cost, such as reducing the number of faces of all generated objects or instantiating all objects with lower density.

**Comment by araistrick** [comment]
There are some options to reduce mesh resolution in `docs/ConfiguringInfinigen.md`. The biggest barrier here though is realizing instanced objects (grass/rocks etc). I discussed some options RE instancing in #108. 

If you are OK with very very low mesh resolution then you do have the legitimate option of implementing the following: `butil.modify_mesh('DECIMATE'...)` on all objects inside of `assets:` collections, then enumerating all `scatter:` objects, inserting RealizeInstances nodes into their graphs, then applying modifiers on those objects.

**Comment by Inshsang** [comment]
Thank you ever so much for taking the time to respond.  I have successfully managed to export the scene I had envisioned. Your expertise and dedication in developing this outstanding project are greatly appreciated. I feel fortunate to have access to such a wonderful tool, and I cannot thank you and your team enough for your valuable contributions

**Comment by enor2017** [comment]
> Thank you ever so much for taking the time to respond. I have successfully managed to export the scene I had envisioned. Your expertise and dedication in developing this outstanding project are greatly appreciated. I feel fortunate to have access to such a wonderful tool, and I cannot thank you and your team enough for your valuable contributions

Hi, I am pretty interested in how you solved this problem. May I have some simple instructions on how you exported the scene? Thank you so much!
