### ISSUE TITLE
[REQUEST] file "generate_individual_assets.py" 

### ISSUE THREAD

**Issue by Dianazero** [princeton-vl/infinigen#119]
**Describe the feature you would like to see implemented**

Hello，I attempt to generate some individual assets following the documentation, but there is no file name "generate_individual_assets.py" in “worldgen/tools” directory.  May I ask where I can find this script？Thanks！

**Comment by araistrick** [comment]
Im not sure how this happened, the file you should use is `worldgen/tools/asset_grid.py`. I am certain I renamed it but the change may have gotten lost while rebasing, my apologies. I will leave this issue open until I correctly rename the file in 1.0.3

**Comment by Dianazero** [comment]
Got it, thank you for your friendly reply.

**Comment by araistrick** [comment]
This is patched on main as part of #132
