### ISSUE TITLE
[REQUEST] Try out on Infinigen

### ISSUE THREAD

**Issue by Sugarman** [princeton-vl/infinigen#120]
**Describe the feature you would like to see implemented**
hi, I'm Sugarman and I am a producer based in China. I am thrilled to see the capacity of infinigen and would like to try out. I wonder if I can use on my mac OS system. I am good at blender btw. Thank you and hope to hear from your team

**Comment by araistrick** [comment]
Yes, you should be able to follow the Installation and HelloWorld instructions linked in our README to test out Infinigen. Please followup if you have any issues

**Comment by Sugarman** [comment]
hi! Thanks a lot for the reply! I thought it only worked on windows since there is only one tutorial on youtube, which is installed on windows lol. But thanks!
