### ISSUE TITLE
When I run: $BLENDER - noaudio -- background -- Python generate. py -- seed 0-- task coat - g desert.gin simple.gin -- output_ Folder outputs/helloworld/coat

### ISSUE THREAD

**Issue by shiyashen** [princeton-vl/infinigen#131]
**Describe the bug**
AWhen I run: $BLENDER - noaudio -- background -- Python generate. py -- seed 0-- task coat - g desert.gin simple.gin -- output_ Folder outputs/helloworld/coat

An error message occurred: - noaudio: Command not found

the  "install.py "  have installed Blender in the infinigenm directory and can manually open it.

**Steps to Reproduce**'

- What command did you run?
```
Add your command here
```$BLENDER - noaudio -- background -- Python generate. py -- seed 0-- task coat - g desert.gin simple.gin -- output_ Folder outputs/helloworld/coat

- What are your output logs? 
```No log file generated
A
** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**

 no error
`

**Platform**
- OS & OS Version: Ubuntu 22.04.3 LTS
- GPU (?) : nvidia P6000
- GPU Driver Version (?) :w-3245
- RAM (GB):384G

**Additional context**
Add any other context about the problem here.

**Comment by araistrick** [comment]
Hello, please make sure you followed the step in our Installation guide to add `export BLENDER=...` to you terminal/bashrc. This error occurs when `echo $BLENDER` is empty, so it is likely that you did not correctly configure the $BLENDER variable.
