### ISSUE TITLE
low polygon of outside rendering

### ISSUE THREAD

**Issue by fisherss** [princeton-vl/infinigen#133]
I've generated a fine scene with:
```
$BLENDER -noaudio --background --python generate.py -- --seed 123 --task coarse -g desert.gin simple.gin --output_folder outputs/helloworld/coarse
```
```
$BLENDER -noaudio --background --python generate.py -- --seed 123 --task populate fine_terrain -g desert.gin simple.gin --input_folder outputs/helloworld/coarse --output_folder outputs/helloworld/fine
```
but I got different results with following command and independent blender:
```
$BLENDER -noaudio --background --python generate.py -- --seed 123 --task render -g desert.gin simple.gin --input_folder outputs/helloworld/fine --output_folder outputs/helloworld/frames
```
![1](https://github.com/princeton-vl/infinigen/assets/49359331/3b118e02-96dd-4816-9b7e-e5bc2fa2cd92)
![2](https://github.com/princeton-vl/infinigen/assets/49359331/5065eac2-d2d1-4ec4-8ada-14db6d5a1158)

As you can see the hole is obviously very low polygon(outside rendering), what did I miss to use an independent blender?

**Comment by araistrick** [comment]
We hide the high poly meshes in the viewport by default, or else it can be very laggy and hard to work with. You can unhide all meshes or just the meshes you care about using the technique shown here: https://github.com/princeton-vl/infinigen/issues/94#issuecomment-1628355817

**Comment by fisherss** [comment]
Thank you araistrick, but I still getting the problem, my hiding/unhiding setting:

![3](https://github.com/princeton-vl/infinigen/assets/49359331/6ad2be51-c37d-4e82-9725-fdd73ade7f9f)

and I found that if remove all files but MaskTag.json and scene.blend, even infinigen's script got the same result(low poly), did I miss OpaqueTerrain.glb in blender?

**Comment by araistrick** [comment]
Ah apologies, yes, due to a recent optimization it is now the case that OpaqueTerrain.glb is not loaded into the blend by default, to avoid the data being duplicated across both the blend and glb when running tons of jobs. For now you may need to import it through the blender UI to see the full scene. This will be fixed in 1.1

**Comment by fisherss** [comment]
May I ask 1.1 release date?

**Comment by araistrick** [comment]
v1.1 is slated for early september on infinigen.org/roadmap, but we may patch this sooner. Until then, the best option is importing the glb, and this can be done automatically using bpy.ops. 

I will leave this open until we add a flag to include the glb by default

**Comment by araistrick** [comment]
Apologies again for this issue, it is more of a problem than I realized as the terrain glbs are split into multiple parts for the ground, atmosphere and liquids etc, and importing them through blender does not automatically set up the materials correctly. 

We will release a patch shortly to include them by default.
