### ISSUE TITLE
Error: No module named 'flip_fluids_addon',Error:

### ISSUE THREAD

**Issue by wb175208** [princeton-vl/infinigen#136]
executive command：

python -m tools.manage_datagen_jobs --specific_seed 3930249d --output_folder outputs/fire --num_scenes 1 --pipeline_config local_256GB.gin monocular_video.gin --cleanup none --config plain.gin fast_terrain_assets.gin use_on_the_fly_fire.gin

result：

......
------------------------------------------------------------
outputs/fire 08/28 11:39AM -> 08/28 01:02PM
============================================================
concurrent_max                 : 16
crashed/populate               : 1
crashed/total                  : 1
disk_usage                     : 0.4
n_in_flight                    : 1
n_launching                    : 15
running/backuppopulate         : 1
running/total                  : 1
succeeded/coarse               : 1
succeeded/total                : 1
------------------------------------------------------------
outputs/fire 08/28 11:39AM -> 08/28 01:02PM
============================================================
concurrent_max                 : 16
crashed/populate               : 1
crashed/total                  : 1
disk_usage                     : 0.4
n_in_flight                    : 1
n_launching                    : 15
running/backuppopulate         : 1
running/total                  : 1
succeeded/coarse               : 1
succeeded/total                : 1
------------------------------------------------------------
outputs/fire 08/28 11:39AM -> 08/28 01:02PM
Crashed: 3930249d backuppopulate 46995112506 None Error: No module named 'flip_fluids_addon',Error: Traceback (most recent call last):,Error: No module named 'flip_fluids_addon' fatal=True 08/28 01:02PM

============================================================
concurrent_max                 : 16
crashed/backuppopulate         : 1
crashed/populate               : 1
crashed/total                  : 2
disk_usage                     : 0.4
n_in_flight                    : 0
n_launching                    : 16
succeeded/coarse               : 1
succeeded/total                : 1
------------------------------------------------------------

Ubuntu 20.04 + RAM32G + 3070ti

so,What happened?thanks!

**Comment by liwei0705** [comment]
try "bash install.sh flip_fluids"

**Comment by wb175208** [comment]
> try "bash install.sh flip_fluids"


I have already done it，but not use

**Comment by wb175208** [comment]
I think it maybe a problem with the location of the plugin folder

**Comment by liwei0705** [comment]
make sure no error logs during the installation.
