### ISSUE TITLE
Textures baked inversely during export

### ISSUE THREAD

**Issue by aplatyps** [princeton-vl/infinigen#141]
Hi @David-Yan1 :) I saw that the file  `infinigen/worldgen/tools/export/export.py` is written by you. I think the textures are baked inversely. I tried exporting an asset's (e.g. a flower) mesh and texture after generating via `infinigen/worldgen/tools/generate_individual_assets.py` and noticed all the textures are upside-down. Could you help take a quick look at it? Thanks!

An example would be as below:
https://github.com/princeton-vl/infinigen/assets/103926799/7c06a52c-d953-49bd-8a90-11afedd43fb9

## Steps to Reproduce
Run `infinigen/worldgen/tools/export/export.py` on a .blend file generated via `infinigen/worldgen/tools/generate_individual_assets.py`

Version of the code were you using?  : latest

### Platform
- OS & OS Version: Linux
- GPU (?) : Tesla T4
- GPU Driver Version (?) :  Driver Version: 510.47.03    CUDA Version: 11.6 
- RAM (GB): 16GB

**Comment by David-Yan1** [comment]
Which file format were you trying to export to?

**Comment by aplatyps** [comment]
.obj .mtl and .png

**Comment by David-Yan1** [comment]
Ah, this seems to be an issue on MeshLab's end, which is what I assume you are using based off of the video. Try changing the Render settings for "Back-face" from Single to Double.

Before:
<img width="1443" alt="image" src="https://github.com/princeton-vl/infinigen/assets/113140835/44eac7c4-43b9-434d-b680-ceaeb268b701">

After:
<img width="1460" alt="image" src="https://github.com/princeton-vl/infinigen/assets/113140835/f629bbb2-54af-4f99-8b5f-3a9133b28f22">

**Comment by aplatyps** [comment]
Ah, I got the inverted texture when visualising it with Trimesh library and Pyrender as well. Maybe they're not compatible with the way bpy encode the faces information.

![Screenshot 2023-09-04 at 10 52 01 PM](https://github.com/princeton-vl/infinigen/assets/103926799/352ad14f-8256-4779-973d-09acb4173cba)

**Comment by David-Yan1** [comment]
Could you send the original blend file and exported zip if possible? Could not replicate the error locally.

**Comment by aplatyps** [comment]
Here you go

[flower.zip](https://github.com/princeton-vl/infinigen/files/12514820/flower.zip)

**Comment by David-Yan1** [comment]
At least from what I can see, the textures are not inverted when I do a side by side comparison of the objects. It seems to me the "upwards" part of the flower being dark is caused by a simple lack of illumination on that face (as I can just about replicate it if I turn off all light sources in Blender). We don't bake the scene lighting into the exported textures, so you'll have to add lighting in your renderer of choice. 

<img width="896" alt="image" src="https://github.com/princeton-vl/infinigen/assets/113140835/922a8037-a434-48fb-babb-f121e8b3d50f">

**Comment by aplatyps** [comment]
I see, that explains it! I just need to find a way to illuminate the top part then. Thanks for the promptly replies :)
