### ISSUE TITLE
when running the hello world, it outputs error:RuntimeError: Error: Cannot read file '/home/lando/infinigen/worldgen/outputs/helloworld/fine/scene.blend': No such file or directory

### ISSUE THREAD

**Issue by 1581967825** [princeton-vl/infinigen#143]
# Describe the bug

when running the hello world, it outputs error:RuntimeError: Error: Cannot read file '/home/lando/infinigen/worldgen/outputs/helloworld/fine/scene.blend': No such file or directory

### What command did you run?
```
I just use the hello world command in the instructions. And I fully install the install.sh .```

### What are your FULL output logs?
```

```
![截图 2023-09-20 15-43-01](https://github.com/princeton-vl/infinigen/assets/102127855/781c96af-8353-459a-b480-c61281a924c1)

**Comment by araistrick** [comment]
Hello, this error seems like it would come from the third command in our hello world steps. Please post the full output logs from the first two as attachments so I can find the error. It is likely that something just failed earlier in the pipeline

**Comment by 1581967825** [comment]
Thanks a lot. There is a problem in the first code. And I have solved problem according to the previous issue.
