### ISSUE TITLE
[REQUEST] Generate fruits, vegetables and flowers as individual assets

### ISSUE THREAD

**Issue by ghpkishore** [princeton-vl/infinigen#150]
**Describe the feature you would like to see implemented**

In the trees, there have to be some fruits and vegetables and flowers. I want these assets independently as well, to ensure that we can populate or simulate them falling onto the ground in a scene. I searched in the roadmap that there will be consistent release of generated assets and couldnt find them. Request you to release some models soon.

**Comment by araistrick** [comment]
Hello, the best way to get these assets independently is to use our docs/GeneratingIndividualAssets.md. For most users this will be quicker and more flexible than downloading pre-generated assets. Our initial data release coming soon will not feature any pre-generated individual assets, but I will consider adding this in a future release.
