### ISSUE TITLE
generation controls for 3d scene

### ISSUE THREAD

**Issue by yujilin** [princeton-vl/infinigen#151]
Thanks for your interesting work! I am trying to use the infinigen to generate photorealistic underwater scenes. But I've encountered some of the following difficulties, some of which I'm already working on but others I haven't figured out yet.

1. The scene I want to generate do not need a lot of assets or a large area, which I could not operate the scene on my PC. So I followe the issue #71 to reduce the bounding box and use the config `dev.gin`. But the density of assets is still so high that I'm not sure if this is what limits my local real-time operation. Is there any configs other than [Config Overrides for mesh detail and performance](https://github.com/princeton-vl/infinigen/issues/new?assignees=&labels=enhancement&projects=&template=request.md&title=#config-overrides-for-mesh-detail-and-performance) that can directly adjust the density of assets?

2. I want to generate different color attenuation for one underwater scene. Could you provide any insights on adjusting the water color (or water absorption of lighting), specifically, minimizing the impact of water on the color of underwater assets.

**Comment by araistrick** [comment]
Hello, 

What assets in particular are too dense for your liking? unfortunately there is not a global asset density control at the moment, you would need to tune the density manually. You can find the settings for the assets that interest you by reading through `worldgen/generate.py` to find the code that adds each type of asset and using gin or adjusting the python keyword arguments as necessary.

To adjust the attenuation / volume shading effects of underwater scenes you would want to edit/configure [water.py](https://github.com/princeton-vl/infinigen/blob/a8ba86a394f8757586b4fb15252a3282e56a91de/worldgen/surfaces/templates/water.py#L170)'s volume shading settings. The function is marked @gin.configurable, so you can use a gin override (as described in docs/ConfiguringInfinigen.md) to set `water.shader.volume_density=0` if you wanted to remove underwater volume effects altogether.

Apologies that  there arent currently easier high-level controls for this, but hopefully this achieves your two goals

**Comment by yujilin** [comment]
Thank you for your response!

I am taking those two issues with your guidance. Now I have another issue. I try to generate two same scenes with one seed, but I get two different scenes. SO the same seed  is not equal to the same scene? Or is there any way to get the same scenes for two generation?

Once again, thank you for your time and your assistance!

**Comment by yujilin** [comment]
Ok, I keep the seed of numpy still and then the scene will be the same across two generation.

**Comment by araistrick** [comment]
`worldgen/configs/base.gin` contains a config `camera.spawn_camera_rigs.n_camera_rigs = 1` which you can modify or override from the commandline

**Comment by araistrick** [comment]
Resolving due to inactivity

**Comment by yujilin** [comment]
Now, I have a problem that I have added a control `compose_scene.fish_school_chance=1.0` in command line. But there is no fishes in generated scene.
