### ISSUE TITLE
Error: 'numpy._DTypeMeta' object is not subscriptable"

### ISSUE THREAD

**Issue by XeuniceX** [princeton-vl/infinigen#156]
[Infinigen Hello World.txt](https://github.com/princeton-vl/infinigen/files/13125605/Infinigen.Hello.World.txt)

**Comment by init-qy** [comment]
Try this: https://github.com/princeton-vl/infinigen/issues/130#issuecomment-1776938036

**Comment by XeuniceX** [comment]
> Try this: [#130 (comment)](https://github.com/princeton-vl/infinigen/issues/130#issuecomment-1776938036)

my version is already changed to that, but I still get the same error

**Comment by SongOnWater** [comment]
use  numpy==1.23.5 in requirement.txt

**Comment by XeuniceX** [comment]
> use numpy==1.23.5 in requirement.txt

still getting the same error :(

**Comment by SongOnWater** [comment]
I think you are using a Mac, there will be multiple Python interpreters ( Python environment
) on your Mac, as Mac has one Python in OSX by default ,  and Blender has one with itself( inside Package Content) , if you has used "brew install python " or likely , Brew installs a Python , and Inifigen use "conda" it will also create a Python environment.  After you set "numpy==1.23.5" you should run "bash install.sh" again  or use the Python inside Blender to reinstall numpy , such as "/infinigen/Blender.app/Contents/Resources/3.3/python/bin/pip install  numpy==1.23.5" .

**Comment by XeuniceX** [comment]
> I think you are using a Mac, there will be multiple Python interpreters ( Python environment ) on your Mac, as Mac has one Python in OSX by default , and Blender has one with itself( inside Package Content) , if you has used "brew install python " or likely , Brew installs a Python , and Inifigen use "conda" it will also create a Python environment. After you set "numpy==1.23.5" you should run "bash install.sh" again or use the Python inside Blender to reinstall numpy , such as "/infinigen/Blender.app/Contents/Resources/3.3/python/bin/pip install numpy==1.23.5" .

Thank you so much, it worked
