### ISSUE TITLE
How to configure debug in vs code, need some docs

### ISSUE THREAD

**Issue by everbboy** [princeton-vl/infinigen#157]
**Describe the feature you would like to see implemented**

**Comment by araistrick** [comment]
On v1.0.4 infinigen uses blenders python interpreter, which can be executed via 'blender/blender --python <script name.py>'. Vscode allows you to configure python.defaultInterpreterPath or similar so you may be able to set it to this.

We also have an upcoming version of Infinigen on the rc1.1.1 branch which is installed via pip and uses the user's default python. It is not yet well tested but may suffice, and has the benefit that you can use your normal python debugging workflow.

**Comment by everbboy** [comment]
hi, araistrick, i have done some tries these days, but all failed. :( as i am not familiar with python development.

**Comment by everbboy** [comment]
if anyone could kindly tell me how to configure vscode to debug infinigen please?

**Comment by araistrick** [comment]
If you are not overly familiar with python development then i recommend going the 1.1.1 route I mentioned. Do `git checkout rc1.1.1` then follow the install instructions on that branch. If you follow these steps, then infinigen will be just like any other python package.

**Comment by everbboy** [comment]
hi araistrick, i got the 1.1.1 branch, but encountered the same problem when i tried to debug it in vs code, the terminal throws the "ModuleNotFoundError: No module named 'bpy'". ==!

**Comment by everbboy** [comment]
oh, the branch 1.1.1 can debug in vscode now, it seems i forgot to change vscode's python interpreter after i changed to this branch. Thank you so much! araistrick. haha.
