### ISSUE TITLE
Any chance to run it on Windows? (whining here!)

### ISSUE THREAD

**Issue by OndeNoHay** [princeton-vl/infinigen#16]
That's it! I confess I am a total failure with Linux. I suppose I should have paid more attention at school then!

So, as a Windows user, will I ever be able to see this working on my pc?

Thanks a lot!

**Comment by araistrick** [comment]
Some users have had success installing the project under Windows Subsystem for Linux (WSL), detailed instructions on this will be coming soon. Running the system natively on Windows is in theory possible - Python and Blender both support Windows. However, we have not yet developed thorough instructions for compiling the terrain system on Windows, and this may take some time.

Follow us here for news https://twitter.com/princetonvl
