### ISSUE TITLE
reason='Error: Cannot read file "/opt/ai3d/infinigen/outputs/hello_world_one_cmd/0/fine/scene.blend": No such file or directory

### ISSUE THREAD

**Issue by toughChow** [princeton-vl/infinigen#181]
# Describe the bug
Run one cmd occurs error.

### What command did you run?
python -m infinigen.datagen.manage_jobs --output_folder outputs/hello_world_one_cmd --num_scenes 1 --specific_seed 0 --configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False

### What are your FULL output logs?
outputs/hello_world_one_cmd 12/16 04:59PM -> 12/16 05:02PM
Crashed: 12/16 05:02PM outputs/hello_world_one_cmd/0/logs/backuppopulate.err reason='Error: Cannot read file "/opt/ai3d/infinigen/outputs/hello_world_one_cmd/0/fine/scene.blend": No such file or directory,Error: Error: Cannot read file "/opt/ai3d/infinigen/outputs/hello_world_one_cmd/0/fine/scene.blend": No such file or directory' node=None fatal=True

### Platform
- OS & OS Version:  Ubuntu22
- RAM (GB): 8

**Comment by araistrick** [comment]
Should be fixed, apologies for the issue.
