### ISSUE TITLE
 Object 'OpaqueTerrain' can't be selected because it is not in View Layer 'ViewLayer'!

### ISSUE THREAD

**Issue by toughChow** [princeton-vl/infinigen#183]
# Describe the bug
Error occurs when I execute one line command!

### What version of the code were you using? 
latest version

### What command did you run?
python -m infinigen.datagen.manage_jobs --output_folder outputs/hello_world_one_cmd --num_scenes 1 --specific_seed 0 --configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False

### What are your FULL output logs?
------------------------------------------------------------
outputs/hello_world_one_cmd 12/18 01:06AM -> 12/18 01:07AM
============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.24
control_state/n_in_flight      : 1
control_state/try_to_launch    : 0
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/hello_world_one_cmd 12/18 01:06AM -> 12/18 01:07AM
Crashed: 12/18 01:07AM outputs/hello_world_one_cmd/0/logs/coarse.err reason="Error: Object 'OpaqueTerrain' can't be selected because it is not in View Layer 'ViewLayer'!,Error: Error: Object 'OpaqueTerrain' can't be selected because it is not in View Layer 'ViewLayer'!" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.24
control_state/n_in_flight      : 0
control_state/try_to_launch    : 1
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------

**Comment by araistrick** [comment]
Very sorry for the issue again, this is a bug from the latest hotfix and im not sure how it slipped through. I will push a fix shortly.
