### ISSUE TITLE
License should be GPL for using bpy

### ISSUE THREAD

**Issue by kuonangzhe** [princeton-vl/infinigen#193]
# Describe the bug
The license shown is now BSD, which looks friendly. While the source code is using bpy, the python sdk for blender, as well as other libs like blenderproc, and they are all licensed under GPL 3.0. 

Based on rules of GPL 3.0, all derived code work should be released under the same license.

**Comment by jiadeng** [comment]
GPL rules require our license to be "GPL compatible", which is not the same as "GPL". BSD is GPL compatible. Your understanding of GPL rules is incorrect.
