### ISSUE TITLE
Can't Install Infinigen as a Blender Python script

### ISSUE THREAD

**Issue by FelixHSS** [princeton-vl/infinigen#205]
# Describe the bug
Branch doesn't exist

## Steps to Reproduce
> git clone https://github.com/princeton-vl/infinigen.git -b rc_1.1.1
> Cloning into 'infinigen'...
> fatal: Remote branch rc_1.1.1 not found in upstream origin

### What command did you run?
git clone https://github.com/princeton-vl/infinigen.git -b rc_1.1.1

**Comment by araistrick** [comment]
Apologies, the `-b rc_1.1.1` should be removed, please try again without this and I will update the docs
