### ISSUE TITLE
How to adjust FPS

### ISSUE THREAD

**Issue by xichenpan** [princeton-vl/infinigen#209]
**Describe the feature you would like to see implemented**

Hi @araistrick, thanks for the great work! How can I adjust FPS in the rendered video?

I just browsered https://github.com/princeton-vl/infinigen/blob/main/infinigen_examples/configs/base.gin, but only find execute_tasks.frame_range, you mentioned in the https://github.com/princeton-vl/infinigen/blob/main/docs/ConfiguringInfinigen.md that this repo use 24 fps by default. How can I change the FPS to higher?

**Comment by araistrick** [comment]
Hello,

There isn't a gin config setting for it in the current public version, although coincidentally I have added one in v1.3 which will release soon.

In the meantime, you can just add `bpy.context.scene.render.fps=100` to the start the `compose_scene` function in `generate_nature.py`
