### ISSUE TITLE
How to specify GPUs?

### ISSUE THREAD

**Issue by zitianlll** [princeton-vl/infinigen#212]
**Describe the feature you would like to see implemented**

I want to run the generation job on the specified gpus(such as 4,5,6,7) of our 8*a100 sever, while the commd`screen python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos --num_scenes 100 \
    --pipeline_config local_256GB monocular_video cuda_terrain blender_gt \
    --cleanup big_files --warmup_sec 60000 --config video high_quality_terrain` would assign each tasks to each GPU. I have tried the code such as `CUDA_VISIBLE_DEVICES=4`, but it seems to be useless.

**Comment by araistrick** [comment]
Hello,

`local_256GB` is intended to respect CUDA_VISIBLE_DEVICES, although the current implementation would expect a comma separated list of integers IE `CUDA_VISIBLE_DEVICES=4,5,6,7`. The code which parses this is [here ](https://github.com/princeton-vl/infinigen/blob/5132903cd68704367d1c44c841e5163158e0f33d/infinigen/datagen/util/submitit_emulator.py#L158)

The logs should also contain what setting of CUDA_VISIBLE_DEVICES each job actually observed, which gets printed by [this](https://github.com/princeton-vl/infinigen/blob/5132903cd68704367d1c44c841e5163158e0f33d/infinigen/core/execute_tasks.py#L407C7-L407C82) line. Please check the results of this print statement in your `coarse.out` logs and let me know what it says so we can continue with debugging

**Comment by araistrick** [comment]
Hello, apologies for the delay, I have a patch for this and will release it shortly.

**Comment by araistrick** [comment]
should be fixed.
