### ISSUE TITLE
Could not build wheels for infinigen, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by original-doc** [princeton-vl/infinigen#221]
# Describe the bug
install failes when using pip install -e .

## Steps to Reproduce
This is my install process:
conda install conda-forge::gxx=11.4.0 mesalib glew glm menpo::glfw3
export C_INCLUDE_PATH=$CONDA_PREFIX/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$CONDA_PREFIX/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

git clone https://github.com/princeton-vl/infinigen.git
cd infinigen
conda create --name infinigen python=3.10
conda activate infinigen

pip install -e .
and it get this error

### Attachment of the logs.txt
[logs.txt](https://github.com/princeton-vl/infinigen/files/15051712/logs.txt)

### Platform
- OS & OS Version: Ubuntu 22.04
- GPU (?) : 3090 *4
- GPU Driver Version (?) :CUDA 12.0

**Comment by araistrick** [comment]
@mazeyu terrain compile is failing.
@original-doc can you just run `make terrain` and provide the logs?

**Comment by original-doc** [comment]
Thank you, I just solved by modifing compile_terrain.sh to alias nx="$nvcc_location -O3 -Xcompiler -fPIC -shared -std=c++11"

> @mazeyu terrain compile is failing. @original-doc can you just run `make terrain` and provide the logs?

**Comment by original-doc** [comment]
In line 41 of the compile_terrain.sh, would you please consider add this in the main  branch? @araistrick 
> Thank you, I just solved by modifing compile_terrain.sh to alias nx="$nvcc_location -O3 -Xcompiler -fPIC -shared -std=c++11"
> 
> > @mazeyu terrain compile is failing. @original-doc can you just run `make terrain` and provide the logs?

**Comment by original-doc** [comment]
solved by modifing compile_terrain.sh to alias nx="$nvcc_location -O3 -Xcompiler -fPIC -shared -std=c++11" In line 41
