### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by diaohonghui** [princeton-vl/infinigen#23]
**Describe the bug**

**Steps to Reproduce**
- What version of the code were you using? Tell us the output of `git log -n 1`
'''
$ git log -n 1
commit 6ce8234cc8e3bf71a9e345f2b9014245e9b6e3c1
'''

- What command did you run?
```
bash install.sh
```

- What are your output logs? 
```
install.sh: line 2: $'\r': command not found
install.sh: line 23: syntax error near unexpected token `elif'
'nstall.sh: line 23: `elif [ "${OS}" = "Darwin" ]; then
```

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**
```
Add your install.sh logs here
```

**Platform**
- OS & OS Version: win11
- GPU (?) : 12900k
- GPU Driver Version (?) :536.23
- RAM (GB):64

**Additional context**

**Comment by araistrick** [comment]
Hello, please provide full logs so we can help

**Comment by David-Yan1** [comment]
Hi, it seems that you are trying to compile Infinigen natively on Windows, which we currently do not support. We are working on this currently, but for now we recommend using [WSL2](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview). A full guide on Windows installation will be coming very soon.
