### ISSUE TITLE
Creatures: code to export new nurbs creature bodies

### ISSUE THREAD

**Issue by hdoi5324** [princeton-vl/infinigen#238]
**Describe the feature you would like to see implemented**

I would like to create new nurbs body file similar to body_fish_puffer.npy.  I have updated an existing nurbs body in Blender but I'm not sure how to export the nurbs data into the npy file that the creature code uses.  I looked at the code in creature_parser->parse_part but I'm not sure whether I should be saving the handles or the profiles_ns.  Thanks for your help.

**Comment by araistrick** [comment]
Hi, sorry this wasn't released, I thought it was part of parse_part but it was actually an extra little script. Ive pushed it on the `f_creature_parser` branch.

**Comment by hdoi5324** [comment]
Thanks for the quick response!
