### ISSUE TITLE
I already have a mesh of some buildings, can I use infinigen to generate textures

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [princeton-vl/infinigen#243]
I already have a mesh of some buildings, can I use infinigen to generate textures

**Comment by araistrick** [comment]
You can certainly try calling the .apply() function of some of our `infinigen/assets/materials` files on some of your building objects, and it will apply a material. But it will not react to the geometry in any particular way unless you code this yourself. Infinigen also broadly doesnt cover urban / building materials currently.
