### ISSUE TITLE
Camera focal length

### ISSUE THREAD

**Issue by TomTomTommi** [princeton-vl/infinigen#244]
Hi, is there a script to convert depth to disparity for stereo methods training? (Maybe similar to use `disparity=focal length*baseline/depth` ?)

Plus, I see `baseline` in `base.gin`, how can I find and set `focal length`?

**Comment by lahavlipson** [comment]
You can set the focal length (in mm) through gin-config, e.g.,`execute_tasks.focal_length=100`

To obtain/set the focal length in pixels, you need to multiply by the `conversion_factor`:
```
conversion_factor = bpy.context.scene.render.resolution_x / camera.data.sensor_width
```

We export the depth, camera poses and camera intrinsics for the left and right cameras. So you need to compute the disparity manually using the equation you mention.

**Comment by TomTomTommi** [comment]
Thanks for your response. I tried a demo, but the output seems weird. @araistrick 

I read a piece of specific camera info from `camera_0/*.npz` and `camera_1/*.npz`, and obtained following info:

left and right camera K (the same)
```
[[2.0e+03 0.0e+00 6.4e+02]
[0.0e+00 2.0e+03 3.6e+02]
[0.0e+00 0.0e+00 1.0e+00]]
```
left camera RT
```
[[-7.97898918e-02  3.61784436e-02  9.96154964e-01 -1.26663132e+01]
 [-9.96811688e-01 -2.89590703e-03 -7.97373205e-02 -2.90765896e+01]
 [ 0.00000000e+00 -9.99341130e-01  3.62941623e-02  2.39611745e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```
right camera RT
```
[[-7.97898918e-02  3.61784436e-02  9.96154964e-01 -1.26722975e+01]
 [-9.96811688e-01 -2.89590703e-03 -7.97373205e-02 -2.91513500e+01]
 [ 0.00000000e+00 -9.99341130e-01  3.62941623e-02  2.39611745e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

I obtain 
the focal length as `focal_length = camera_left['K'][0][0]` and finally `(focal_length = 2000.0)`;
the baseline as `np.linalg.norm(camera_left['T'][:3, 3] - camera_right['T'][:3, 3])` and finally `(baseline = 0.074999565762074)`

then, the disparity is:
```
disparity = focal_length * baseline / depth
normalized_disparity_map = np.clip(disparity, 0, 256)
int_disparity_map = (normalized_disparity_map * (256.0 / 256)).astype(np.uint8)
```
But the final result of disparity is 
```
[[0 0 0 ... 7 7 7]
 [0 0 0 ... 7 7 7]
 [0 0 0 ... 7 7 7]
 ...
 [9 9 9 ... 8 8 8]
 [9 9 9 ... 8 8 8]
 [9 9 9 ... 8 8 8]]
```
I wonder which step is wrong.
