### ISSUE TITLE
Reproducing weather simulation results

### ISSUE THREAD

**Issue by zhihao-lin** [princeton-vl/infinigen#261]
# Describe the bug
Hi @araistrick, thank you for the excellent work, and the demo video looks fantastic! Currently, I am trying to reproduce the weather effects (e.g. rain, snow) that are demonstrated in the video [1:05](https://www.youtube.com/watch?v=6tgspeI-GHY&t=65s), [2:07](https://www.youtube.com/watch?v=6tgspeI-GHY&t=127s), but unfortunately, the results I generated are not as good as expected. As a result, I have some questions regarding this issue:
- What are the setting configurations used (e.g. `rain_settings()` in infinigen/core/placement/particles.py) in these demo videos?
- Are there any other additional settings, or post-processing procedures to make the realistic rainy videos?

### What command did you run?
I generate the rainy video with the following script:
```
python -m infinigen.datagen.manage_jobs \
    --output_folder outputs/video_rain --num_scenes 1 --specific_seed 0617 \
    --pipeline_configs local_64GB monocular_video cuda_terrain blender_gt \
    --cleanup big_files --warmup_sec 60000 --config high_quality_terrain \
    --overrides compose_scene.rain_particles_chance=1.0
```
and the generated frames are provided below:
https://github.com/princeton-vl/infinigen/assets/39002023/09fbee13-93dc-4a82-b665-03d07376df83
where the dynamic of rain is not temporally continuous and each frame doesn't look like it's rainy.

### Platform
- OS & OS Version: Ubuntu 22.04.4 LTS
- GPU: NVIDIA GeForce RTX 4090
- GPU Driver Version: 555.42.02
- CUDA version: 12.5
- RAM (GB): 125
- VRAM (GB): 24

Thanks for your help!

**Comment by araistrick** [comment]
Hello! The sole issue here (I believe) is the lack of motion blur. We turn this off by default for efficiency and because the ground truth always reflects the non blurred version. You can re-enable it adding 'configure_blender.motion_blur=True' to your --overrides. 

Thanks for the question and providing the reference images, lmk if this does not fix.

**Comment by zhihao-lin** [comment]
Thanks for the prompt response! 
The generated rainy images look more realistic by adding `configure_blender.motion_blur=True` after the --overrides, as shown in the first image below.
One thing I found interesting is that the ground truth also reflects the motion blur, which could be seen in the depth (second image) and normal (third image).

![Image_0_0_0009_0](https://github.com/princeton-vl/infinigen/assets/39002023/236773ff-139b-442d-a673-b604e7fb9998)
![Depth_0_0_0009_0](https://github.com/princeton-vl/infinigen/assets/39002023/4ddf4c82-f601-491e-9e3f-e3073a560570)
![SurfaceNormal_0_0_0009_0](https://github.com/princeton-vl/infinigen/assets/39002023/2c1dee7a-de71-4d8d-a6a8-c440b837448c)

**Comment by zhihao-lin** [comment]
Another thing about the rain simulation is that after applying motion blur, the generation takes much longer time (more than 5.5 hours). I am not sure if this is expected and am wondering if there's any tricks to accelerate.
