### ISSUE TITLE
Bug in create 1 second video clips

### ISSUE THREAD

**Issue by Mu-Yanchen** [princeton-vl/infinigen#263]
# Describe the bug
When I run the **Create 1 second video clips** in the final of ConfiguringInfinigen.md, I met the following bugs:

outputs/my_videos 06/24 04:09PM -> 06/24 04:09PM
Crashed: 06/24 04:09PM outputs/my_videos/2e1b97f4/logs/coarse.err reason="FileNotFoundError:  Could not find video or video in any of [PosixPath('/root/infinigen/infinigen_examples/configs_nature'), PosixPath('/root/infinigen'), PosixPath('.')]" node=None fatal=True

## Steps to Reproduce

run like "Create 1 second video clips" with a little modification
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos --num_scenes 500 \
    --pipeline_config local_16GB.gin monocular_video cuda_terrain opengl_gt \
    --cleanup big_files --warmup_sec 30000 --config video high_quality_terrain \
    --pipeline_overrides iterate_scene_tasks.frame_range=[1,25] --overwrite

### What version of the code were you using? 
git log
commit fb7991e06580639202a4687937082cb63e931eb0 (HEAD -> main, tag: v1.4.0, origin/main, 
origin/HEAD)
Merge: 4c13cdea e9ce81ac
Author: pvl-bot <136786582+pvl-bot@users.noreply.github.com>
Date:   Tue Jun 18 00:38:31 2024 -0700

    Merge pull request #258 from princeton-vl/develop
    
    v1.4.0 - Preliminary release of Infinigen Indoors

commit e9ce81acc6b25d7bfbb5522bc75f97e90edd3228 (origin/develop)
Author: pvl-bot <bot@infinigen.org>
Date:   Mon Jun 17 23:51:41 2024 -0700

    v1.4.0 - Preliminary release of Infinigen Indoors

### What command did you run?
the command in "Create 1 second video clips"

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.
![image](https://github.com/princeton-vl/infinigen/assets/134616835/1b42f725-614a-41b3-94b7-f995702dfcc6)

### Platform
- OS & OS Version: Ubuntu
- GPU :RTX 3090
- GPU Driver Version: 525.105.17
- CUDA version: 12.0
- RAM (GB): 24

Thanks for your help!

**Comment by araistrick** [comment]
Apologies, the command is outdated. You will need to change `video` to `trailer_video`, I will patch this into the next release.

**Comment by Mu-Yanchen** [comment]
Thanks for your reply! I will close this issue
