### ISSUE TITLE
Fail to install Infinigen as a Blender Python script

### ISSUE THREAD

**Issue by Mu-Yanchen** [princeton-vl/infinigen#266]
# Describe the bug
Follow the instruction in Installation.md, I've already installed Infinigen as a Python Module and can run basic files. Now I  want to visulize the blend file in 3D blender UI, so I thought I should install the Blender Python script. But when I install the Infinigen use the commond below, I always meet a killed bug, I will appreciate it if any suggestions can 

```
# Normal install (includes CPU Terrain, and CUDA Terrain if available)
bash scripts/install/interactive_blender.sh
```

### What version of the code were you using? 
git log
commit fb7991e06580639202a4687937082cb63e931eb0 (HEAD -> main, tag: v1.4.0, origin/main, 
origin/HEAD)
Merge: 4c13cdea e9ce81ac
Author: pvl-bot <136786582+pvl-bot@users.noreply.github.com>
Date:   Tue Jun 18 00:38:31 2024 -0700

    Merge pull request #258 from princeton-vl/develop
    
    v1.4.0 - Preliminary release of Infinigen Indoors

commit e9ce81acc6b25d7bfbb5522bc75f97e90edd3228 (origin/develop)
Author: pvl-bot <bot@infinigen.org>
Date:   Mon Jun 17 23:51:41 2024 -0700

    v1.4.0 - Preliminary release of Infinigen Indoors

### What command did you run?
I have completed the process for installing Infinigen as a Python Module and the use the following command
```
bash scripts/install/interactive_blender.sh
```

### What are your FULL output logs?
![image](https://github.com/princeton-vl/infinigen/assets/134616835/ed611845-69a0-420a-a856-2c84a755cb0a)

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -vv -e . > logs.txt 2>&1` and send logs.txt as an attachment.
[logs.txt](https://github.com/user-attachments/files/15963746/logs.txt)

### Platform
- OS & OS Version: Ubuntu
- GPU :RTX 3090
- GPU Driver Version: 525.105.17
- CUDA version: 12.0
- RAM (GB): 24

**Comment by araistrick** [comment]
"Killed" usually means out of memory or some OS-level process death. I unfortunately do not know how to proceed with this issue.

**Comment by Mu-Yanchen** [comment]
Thank you for your prompt reply, I will close the question.
BTW, I have another question  #255 , and I would appreciate receiving your reply
