### ISSUE TITLE
Error during generating individual object

### ISSUE THREAD

**Issue by yuanze1024** [princeton-vl/infinigen#276]
# Describe the bug
It seems that your [tutorial of generating individual object](https://github.com/princeton-vl/infinigen/blob/main/docs/GeneratingIndividualAssets.md) is outdated. 
1. `python -m infinigen.tools.generate_individual_assets --help` doesn't work because the `generate_individual_assets.py` is placed in `infinigen_examples` now.
2. And when I execute `python -m infinigen_examples.generate_individual_assets --output_folder outputs/corals -f CoralFactory -n 8 --save_blend`, in precise it raised: 
```plain
FileNotFoundError: Could not find base.gin or base in any of ['infinigen_examples/configs_indoor']
  In call to configurable 'apply_gin_configs' (<function apply_gin_configs at 0x7efcb4002050>)
```
Anyone can tell me how to run the objectGen correctly?

### What version of the code were you using? 
931d1e5be4d05d92ab120863b4179307165dd4f3

### What command did you run?
```python
python -m infinigen_examples.generate_individual_assets --output_folder outputs/corals -f CoralFactory -n 8 --save_blend
``` 

### What are your FULL output logs?
```python-traceback
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/pfs/users/yuanze/projects/infinigen/infinigen_examples/generate_individual_assets.py", line 667, in <module>
    main(args)
  File "/mnt/pfs/users/yuanze/projects/infinigen/infinigen_examples/generate_individual_assets.py", line 427, in main
    init.apply_gin_configs("infinigen_examples/configs_indoor", skip_unknown=True)
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.10/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.10/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/pfs/users/yuanze/projects/infinigen/infinigen/core/init.py", line 172, in apply_gin_configs
    configs = [find_config(g) for g in ["base.gin"] + configs]
  File "/mnt/pfs/users/yuanze/projects/infinigen/infinigen/core/init.py", line 172, in <listcomp>
    configs = [find_config(g) for g in ["base.gin"] + configs]
  File "/mnt/pfs/users/yuanze/projects/infinigen/infinigen/core/init.py", line 168, in find_config
    raise FileNotFoundError(
FileNotFoundError: Could not find base.gin or base in any of ['infinigen_examples/configs_indoor']
  In call to configurable 'apply_gin_configs' (<function apply_gin_configs at 0x7efcb4002050>)
Error: Not freed memory blocks: 26441, total unfreed memory 8.722607 MB
```

### If this is your first time running Infinigen, what are the full install logs?**
No, I've run the **hello world** and **hello room** before. 

But I have to say that the **hello world** failed which gives me some white cubes instead of trees in the blend in **coarse** stage, and some rendered images in folder, e.g., `image`, `Emit`, and `DiffInd` are all black, while some in `depth` and `segmentation` are plausible. 

Now that I don't really care outdoor scenes, the indoor scene is OK, so I just decide to ignore it.

### Platform
- OS & OS Version: Ubuntu 22
- GPU (?) : A100
- GPU Driver Version (?) : 535.86.10
- RAM (GB): basically not limited (1TB)

# Additional context
I see that you guys merge the InfiniGen-Indoor into this code repository, so I assume maybe that is caused by the inconsistency between doc and codes.

**Comment by Roywangj** [comment]
hi @yuanze1024  i met the same problem,

**Comment by araistrick** [comment]
Sorry for the issue, I push a fix for these shortly

**Comment by araistrick** [comment]
Should be resolved by https://github.com/princeton-vl/infinigen/pull/280, please update to v1.5.1
