### ISSUE TITLE
[BUG] libXi.so.6: cannot open shared object file: No such file or directory when running helloworld scene generation

### ISSUE THREAD

**Issue by AkidioUp** [princeton-vl/infinigen#28]
**Describe the bug**
Running `$BLENDER -noaudio --background --python generate.py -- --seed 1 --task coarse -g arctic simple --output_folder outputs/test01/coarse
`
output error message immediately: **infinigen/blender/blender: error while loading shared libraries: libXi.so.6: cannot open shared object file: No such file or directory**

**Steps to Reproduce**
commit aaa0e8e945a4216efdc7cfd3af095054971c04fd (HEAD -> main, origin/main, origin/HEAD)
Author: pvl-bot <136786582+pvl-bot@users.noreply.github.com>
Date:   Mon Jun 19 16:44:54 2023 -0400

    Update README.md

**Platform**
- OS & OS Version:  Ubuntu 22.04.2 LTS
- RAM (GB): 128

**Comment by rathinho** [comment]
I met this problem as well

**Comment by B3DHawkins** [comment]
I ran into this issue this morning as well. I needed to apt install additional libx libraries:
libxrender-dev
libgl-dev
libxfixes3
libxxf86vm-dev

After installing these I was able to run Blender with the generate script and start working on the issues with generate.py. 😆 Still working through them.

**Comment by SpotInspect** [comment]
Could try this to solve this error:

$sudo apt-get install libxi6

**Comment by AkidioUp** [comment]
> Could you post the full install.sh logs an attachment? Thanks!

Sorry for missing that log. But I've fixed this problem by installing libs suggested bt @B3DHawkins and @SpotInspect , which contains `libxi6`, `libxrender-dev`, `libgl-dev`, and `libxxf86vm-dev`. `libxfixes3` wasn't installed due to `Unable to locate package libfixes3`.

Thanks a lot, dudes.

**Comment by xcFelix** [comment]
> I ran into this issue this morning as well. I needed to apt install additional libx libraries: libxrender-dev libgl-dev libxfixes3 libxxf86vm-dev
> 
> After installing these I was able to run Blender with the generate script and start working on the issues with generate.py. 😆 Still working through them.

thanks for the solution. It work.
