### ISSUE TITLE
Is it possible to obtain panoramas and corresponding annotations, such as depth and normal?

### ISSUE THREAD

**Issue by caozidong** [princeton-vl/infinigen#283]
Hi, thanks for your good work. I wonder if it is possible to obtain panoramas from 360 cameras in this system, and corresponding annotations. The camera utilized in this project is a pinhole camera. I think it would greatly benefit the 360 vision community.

**Comment by araistrick** [comment]
Our system generates blender scenes, and provides default code to render pinhole images. However you are free to replace our pinhole camera with any other type of camera possible in blender, you will just need to code this up yourself as we have not yet added a one-click script for this. 

You will need to investigate online how to add a panoramic camera, or how to emulate one with an array of several pinhole cameras.
