### ISSUE TITLE
Cannot finish the HelloRoom demo

### ISSUE THREAD

**Issue by kerufu** [princeton-vl/infinigen#287]
## Steps to Reproduce
Run the HelloRoom, can get the coarse done, but would crash when run the commands  to render an RGB image and ground truth:
AttributeError: 'CompositorNodeOutputFile' object has no attribute 'format.file_format'
  In call to configurable 'configure_compositor_output' (<function configure_compositor_output at 0x331a69240>) in scope 'full'
  In call to configurable 'render_image' (<function render_image at 0x331a69f30>) in scope 'full'
  In call to configurable 'render' (<function render at 0x331a78ee0>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x331a7a680>)

2 points may be relevant: 
1. when run Hello_World, would freeze at [logging] [INFO] | [meshing OpaqueTerrain]. no error and not finished in 1 hour, so I stopped it
2. when try docker installation, would crashed due to python version requirement like "fire" described in this issue: https://github.com/princeton-vl/infinigen/pull/252

### What version of the code were you using? 
tried both 1.6 and 1.5 release

commit 8d079368c3546bc4b4002dd4a91f649c210583eb (HEAD -> main, tag: v1.6.0, origin/main, origin/HEAD)
Merge: c537e245 0712df61
Author: pvl-bot <bot@infinigen.org>
Date:   Thu Aug 1 18:53:56 2024 -0400

    Merge v1.6.0 from branch 'develop'

commit 0712df61c260fba3e664867c0ef2ca6ff9d6b8b6
Merge: 8c4e30d0 ef328ae4
Author: Alex Raistrick <araistrick@princeton.edu>
Date:   Thu Aug 1 18:41:42 2024 -0400

    Merge pull request #225 from princeton-vl/mesher_version_check
    
    Mesher version check

commit 8c4e30d0dfeac3121861a854ffdbb0a9861aa4d6
Merge: 787feeb1 84880b8f
Author: Alex Raistrick <araistrick@princeton.edu>
Date:   Thu Aug 1 18:36:55 2024 -0400

    Merge pull request #230 from princeton-vl/f_more_format_rules

### What command did you run?

python -m infinigen_examples.generate_nature --seed 0 --task render --input_folder outputs/indoors/coarse --output_folder outputs/indoors/frames

### What are your FULL output logs?
[log.txt](https://github.com/user-attachments/files/16478921/log.txt)

### If this is your first time running Infinigen, what are the full install logs?**
[logs.txt](https://github.com/user-attachments/files/16478932/logs.txt)

### Platform
- OS & OS Version: MacOS 14.5
- GPU (?) : Apple M3 Max
- GPU Driver Version (?) :
- RAM (GB): 128

# Additional context

**Comment by Boltzmachine** [comment]
Same problem

**Comment by JuliaChae** [comment]
I am also having the same issue! Has anyone had luck resolving it?

**Comment by araistrick** [comment]
Hello, sorry for the issue, this was broken in a [recent commit](https://github.com/princeton-vl/infinigen/commit/8c4e30d0dfeac3121861a854ffdbb0a9861aa4d6) but should now be fixed thanks to the patch I just pushed from @mazeyu
