### ISSUE TITLE
Cannot edit hidden object when export to Omniverse

### ISSUE THREAD

**Issue by YandanYang** [princeton-vl/infinigen#288]
## Steps to Reproduce
I just want to export the blender scene into omniverse USD file. And get the error saying
 ```RuntimeError: Operator bpy.ops.object.mode_set.poll() Cannot edit hidden object In call to configurable 'export_curr_scene' ``` when calling `bpy.ops.object.mode_set(mode="EDIT")`.

### What version of the code were you using? 
4a4411e92611d059f2476f4384141de3529d1f9f

### What command did you run?
`python -m infinigen.tools.export --input_folder outputs/indoors/coarse_p --output_folder outputs/my_export_omni -f usdc -r 1024 --omniverse`

### What are your FULL output logs?
[log.txt](https://github.com/user-attachments/files/16536589/log.txt)

### If this is your first time running Infinigen, what are the full install logs?**
[logs.txt](https://github.com/user-attachments/files/16536728/logs.txt)

### Platform
- OS & OS Version:  Ubuntu 22.04
- GPU (?) :    NVIDIA Corporation Device 2684 (rev a1)
- GPU Driver Version (?) :  545.29.06  
- RAM (GB):                
```
               total        used        free      shared  buff/cache   available
Mem:            62Gi        13Gi        20Gi       253Mi        28Gi        48Gi
Swap:          2.0Gi       1.5Gi       558Mi
```

# Additional context

**Comment by David-Yan1** [comment]
Hi,

If possible, could you provide either the blend file or the commands to generate the blend file (found in `run_pipeline.sh`)?

**Comment by YandanYang** [comment]
Hi, I follow the [readme](https://github.com/princeton-vl/infinigen/blob/main/docs/HelloRoom.md) and run this command :
`python -m infinigen_examples.generate_indoors --seed 0 --task coarse --output_folder outputs/indoors/coarse -g fast_solve.gin overhead.gin singleroom.gin -p compose_indoors.terrain_enabled=False compose_indoors.overhead_cam_enabled=True compose_indoors.solve_max_rooms=1 compose_indoors.invisible_room_ceilings_enabled=True compose_indoors.restrict_single_supported_roomtype=True
`

Since the blend file is too large to upload, I provide the screenshot of the scene loaded in blender.
![Screenshot from 2024-08-09 16-33-55](https://github.com/user-attachments/assets/a213fbf7-5fdf-4d22-a119-74fcd42a7f5b)

**Comment by David-Yan1** [comment]
This is likely caused by `compose_indoors.invisible_room_ceilings_enabled=True`. In `export.py`, you can add a conditional  in `split_glass_mats()`, which should fix the problem.

```
 for obj in bpy.data.objects:
        if obj.hide_render or obj.hide_viewport:
            continue
        if any( 
            exclude in obj.name
            for exclude in ["BowlFactory", "CupFactory", "OvenFactory", "BottleFactory"]
        ):
            continue
```

**Comment by YandanYang** [comment]
Thanks for your reply. It works.
I converted it into usd for omniverse successfully.
However, when I try to load the usd with isaac_sim.py,  something is wrong with the texture.
It seems that most of **the texture does not reflect light and becomes dark**.

This is the usd loaded in blender (I modify some light power):
![Screenshot from 2024-08-28 18-56-28](https://github.com/user-attachments/assets/ad00b37d-e80f-4562-b3f2-f47ab1e809e8)
And this is usd loaded in isaac sim (nothing changes when I modify the light):
![Screenshot from 2024-08-28 18-37-45](https://github.com/user-attachments/assets/623cdf79-b037-4040-9d31-8f7391e2025b)
And this is the shader of floor mesh:
![Screenshot from 2024-08-28 18-39-00](https://github.com/user-attachments/assets/f1ca0fac-ff53-44fa-b5d7-b5b6a54423bd)
When I change the shader of floor into the same shader of wall, the floor can reflect light, but with no color:
![Screenshot from 2024-08-28 18-49-00](https://github.com/user-attachments/assets/efe47560-7f4c-4c37-92d0-2f46a9253800)

**Comment by YandanYang** [comment]
I upload the file [here](https://drive.google.com/drive/folders/1snlv5W2QiM2BkBLxJQ8jTkGJSBn_y8cO?usp=sharing).
`coarse_p.zip` is the file before converting to usd.
`export_scene.zip` is the converted omniverse usd.
