### ISSUE TITLE
Add additional objects into a finished scene

### ISSUE THREAD

**Issue by Batwho** [princeton-vl/infinigen#293]
Hello,

I wonder is there an efficient way to add additional objects, e.g. trees/flowers/animals into a finished rendered scene? Or do I have to start from scratch and specify additional objects in .gin format.

**Comment by araistrick** [comment]
The finished scene is a standard blender scene, so you have full control via python to do whatever changes you wish.

If you want to invoke more procedural generators, just import them and execute them at the end of compose_scene, IE something like this:

```python
from infinigen.assets.objects.trees import TreeFactory
from infinigen.assets.objects.grassland import FlowerFactory

# add 1 tree
obj = FlowerFactory(0)()
obj.location = (1, 1, 1) # use whatever loc/rot you want
obj.rotation_euler = (np.pi, 0, 0)

# add 3 flowers
for i in range(3):
    obj  = FlowerFactory(i)()
    obj.location = (1, 2, i)
```

If you want to run extra python a scene without starting from scratch, either open it in the UI and run these in the terminal, or create a python script which opens an existing scene, modifies it, then saves it.

**Comment by Batwho** [comment]
Got it, thank you!
