### ISSUE TITLE
Use existing assets instead of procedural generating them

### ISSUE THREAD

**Issue by Boltzmachine** [princeton-vl/infinigen#294]
Hi, for **indoor scenes** can I use my own assets instead of procedural generating them?

**Comment by araistrick** [comment]
Yes, this is not hard to do, we are working on a guide and will release it when possible.

**Comment by Boltzmachine** [comment]
Thanks a lot for your great effort! But I still want to confirm if my current workaround is good since I am asked to do so.
My strategy is to create a factory and define its `create_asset` method, where I import the obj file of the asset. And I also find that I need to remove it from the `Semantics.RealPlaceholder` list, such that in `sample_rand_placeholder` function it will execute `bbox_from_mesh.bbox_mesh_from_hipoly(gen, inst_seed)`.

Could you provide some suggestions. I really need your help. Thank you!

**Comment by araistrick** [comment]
We now have official docs for this https://github.com/princeton-vl/infinigen/blob/main/docs/StaticAssets.md
