### ISSUE TITLE
Blend files of the Pre-Generated Data

### ISSUE THREAD

**Issue by GCChen97** [princeton-vl/infinigen#297]
Are the .blend files of the `Pre-Generated Data` available? If so, it would be beneficial to the robotics communities as the scenes and objects can be reused in simulators such as Isaac Sim or be converted to other sensor data like LiDAR.

BTW, do you have any suggestions for simulating LiDAR with Infinigen?

**Comment by araistrick** [comment]
We do not have blend files saved for the preliminary datarelease scenes. The next video datarelease we put up also wont have blendfiles, but the 3rd nature video and indoors datareleases should have them.

If I were to attempt simulating Lidar, id combine the whole scene into one BVHTree https://docs.blender.org/api/current/mathutils.bvhtree.html then shoot lots of rays in some pattern to get depths. You can seach the project for existing uses of BVHTrees for examples
