### ISSUE TITLE
Create underwater scene with snake floating

### ISSUE THREAD

**Issue by Batwho** [princeton-vl/infinigen#300]
Hello,

I wonder is it possible to generate an underwater scene with the snake swimming in the middle of the ocean? For now, all snakes generated in the underwater scene are staying on the ground but not floating in the water. I tried manually editing the location in the fine/scene.blend and the rendered image doesn't include the snake at all.

**Comment by araistrick** [comment]
Creating floating snakes should be fairly easy, we actually use very similar code between snakes on floor vs birds in sky. 

I believe all you need to do is `p.location.z += altitude` before running policy_create_bezier_path in SnakeFactory.create_placeholder. This will cause the starting altitude of the placeholder to be higher, and the whole bezier pat will float off the ground. You can look at FlyingBirdFactory in objects/bird.py for reference

**Comment by Batwho** [comment]
Thanks so much! I running code to check. However, is it possible to edit the snake position in the blender Ul to make it float after
getting the coarse.blend? That's easier than updating codes. Or I assume using blender UI will require updating the curve
keyframe positions as well?
Also, I noticed that a curve_slither.snap_curve_to_floor function is [used](https://github.com/princeton-vl/infinigen/blob/main/infinigen/assets/objects/creatures/reptile.py#L578) in SnakeFactory but not in FlyingBird. Will that cause
some issue?

**Comment by araistrick** [comment]
If youre willing to edit via UI then that should be the easiest path, I think you can just find the bezier path and translate it upwards. You may need to translate the snake by the same amount.

Yes, snap_curve_to_floor will likely break any nonzero altitude, good catch.
