### ISSUE TITLE
What is the parameter to get topviews like Figure 11?

### ISSUE THREAD

**Issue by Boltzmachine** [princeton-vl/infinigen#302]
![Screenshot 2024-08-20 at 11 17 33 PM](https://github.com/user-attachments/assets/b5086375-28a9-4368-a4d8-571c15ad9d3e)

I want to get the topview of a single room (Figure 11 in the paper). May I know the command / parameters that give me this?

**Comment by araistrick** [comment]
You can create this topview camera angle with an invisible ceiling by adding `overhead.gin singleroom.gin` to your `--configs`
