### ISSUE TITLE
Error of "Cannot edit hidden object" during export

### ISSUE THREAD

**Issue by GCChen97** [princeton-vl/infinigen#311]
# Describe the bug
```
  File "infinigen/infinigen/tools/export.py", line 124, in split_glass_mats
    bpy.ops.object.mode_set(mode="EDIT")
```

## Steps to Reproduce

Just generate an indoor scene and export it.

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

### What command did you run?
```
python -m infinigen_examples.generate_indoors --seed 2 --task coarse --output_folder outputs/indoors/coarse -g fast_solve.gin singleroom.gin performance/simple.gin -p compose_indoors.terrain_enabled=False compose_indoors.hide_other_rooms_enabled=True compose_indoors.skirting_floor_chance=0.0 compose_indoors.skirting_ceiling_chance=0.0 compose_indoors.restrict_single_supported_roomtype=True

python -m infinigen.tools.export --input_folder outputs/indoors/coarse --output_folder outputs/coarse-2 -f usdc -r 1024 --omniverse
```

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -v -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: Ubuntu 22.04
- GPU (?) : RTX3090
- GPU Driver Version (?) : 535.183.01
- RAM (GB): 128GB

# Additional context
I edited the code:
```
                bpy.context.view_layer.objects.active = obj
                if obj.hide_viewport:
                    continue
                bpy.ops.object.mode_set(mode="EDIT")
```
and it can run. But I am not sure if this change is valid and legal.

**Comment by David-Yan1** [comment]
Likely this same issue as #288, I wrote a fix that will be merged eventually
