### ISSUE TITLE
I encountered an error while trying to export USDC

### ISSUE THREAD

**Issue by DreamerYinYu** [princeton-vl/infinigen#312]
Command：
python -m infinigen.datagen.manage_jobs --output_folder outputs/ExportUSDC_05_coast --num_scenes 1 --specific_seed 5 --configs coast.gin simple.gin --pipeline_configs local_256GB.gin monocular.gin export.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False

Error：

outputs/ExportUSDC_07_desert 09/04 11:41AM -> 09/04 11:52AM
Crashed: 09/04 11:52AM outputs/ExportUSDC_07_desert/0/logs/export.err reason='Error:  Evaluated geometry from modifier does not contain a mesh,Error:  Evaluated geometry from modifier does not contain a mesh,Error:  No valid selected objects,RuntimeError: Error:  No valid selected objects' node=None fatal=True

============================================================
control_state/curr_concurrent_max : 3
control_state/disk_usage       : 0.04
control_state/n_in_flight      : 0
control_state/try_to_launch    : 3
control_state/will_launch      : 0
crashed/export                 : 1
crashed/total                  : 1
succeeded/coarse               : 1
succeeded/fineterrain          : 1
succeeded/populate             : 1
succeeded/shortrender          : 1
succeeded/total                : 4

**Comment by christian-jacobsen** [comment]
Currently experiencing the same issue

**Comment by David-Yan1** [comment]
See #309
