### ISSUE TITLE
High quality terrain doesn't look like high-quality？

### ISSUE THREAD

**Issue by DreamerYinYu** [princeton-vl/infinigen#313]
Hello, the high-quality terrain I generated does not appear to be of high quality, and the triangles can be clearly seen. Is there a problem with my command line?

python -m infinigen.datagen.manage_jobs --output_folder outputs/ExportUSDC_01_arctic_high_quality --num_scenes 1 --specific_seed 0 --configs arctic.gin high_quality_terrain.gin --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin export.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False

![微信截图_2024090510062
![微信截图_20240905100624](https://github.com/user-attachments/assets/6f6454d1-74d8-4300-8c2d-041e60f918b2)
4](https://github.com/user-attachments/assets/70fb9a3b-1727-4bfb-9848-c11863bea321)

**Comment by mazeyu** [comment]
We fixed it in the new release. Specifically, as we added in the doc, use `-p fine_terrain.mesher_backend="OcMesher"`.
