### ISSUE TITLE
Specify the locations of creatures in the python command

### ISSUE THREAD

**Issue by Batwho** [princeton-vl/infinigen#315]
Hello,

I wonder is it possible to specify the location of the creature while running the python command. e.g. If I want to create a cave scene with frog sitting cozily next to a fire pit. How could I write such python command? Could writing some extra .gin files help specifying the exact location of the frog and the fire pit?

Appreciate in advance!

**Comment by araistrick** [comment]
gin is intended for highlevel configuration of the existing code, gin-config is not expressive enough to practically specify the locations of individual objects in the scene etc.

Instead you would do the lower level parts via blender's python API, IE loop through bpy.data.objects to find the object you care about, then do `obj.location = xyz` etc to configure its location

**Comment by Batwho** [comment]
I see. Thank you!
