### ISSUE TITLE
Texture bug in isaac sim.

### ISSUE THREAD

**Issue by YandanYang** [princeton-vl/infinigen#322]
# Describe the bug
Hi, I found the problem of texture when loading it in Isaac Sim. Is the texture path saved as absolute or relative?
![362247490-623cdf79-b037-4040-9d31-8f7391e2025b](https://github.com/user-attachments/assets/043e560b-ba06-41e7-9fc4-0d6b10bf337b)
 

## Steps to Reproduce
It happens in two circumstance:
 1) When launch the isaac sim , the `scene-path` must be an absolute path. If it is a relative path, the texture will be lost.
`python examples/isaac_sim.py --scene-path xxx/export_scene.usdc --json-path xxx/solve_state.json
`
2) I try to save the isaac sim project as another .usd file. The exported .usd file works well in the same PC. However, when I load it in another PC, the texture is still missing. Have you tested saving the isaac sim project and load in another PC?

I wonder if you save the texture path as an absolute path during export ? Or maybe it is a bug of Omniverse?
Can you fix this bug and make it work?

### What version of the code were you using? 
4a4411e92611d059f2476f4384141de3529d1f9f

### What command did you run?

`python -m infinigen.tools.export --input_folder outputs/indoors/coarse --output_folder outputs/my_export_omni -f usdc -r 1024 --omniverse`
`python xxx/isaac_sim.py --scene-path xxx/export_scene.usdc --json-path xxx/solve_state.json`

**Comment by YandanYang** [comment]
Hi. I have found the solution. 
Just need to replace the texture path into relative path in the isaac sim before saving into .usd.

**Comment by aditya-nisal** [comment]
> Hi. I have found the solution. Just need to replace the texture path into relative path in the isaac sim before saving into .usd.

Hey YandanYang, do you have any script that would do this automatically for multiple files, instead of manually doing it? Would be really helpful!

**Comment by YandanYang** [comment]
I am sorry I haven't find the automatical way.
If you find the solution, please let me know. I would be very grateful.
