### ISSUE TITLE
Get color attribute for each object

### ISSUE THREAD

**Issue by hpc100** [princeton-vl/infinigen#323]
Hello, 
Thank's for sharing your amazing work.

I'm new in blender field. I would like to know if it's possible to retrieve color directly from scene.blend generated by : `python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True `

With a python code (bpy)

Or I need to create image or export as usdc ?

**Comment by GCChen97** [comment]
What do you mean by "color attribute for each object"? Do you mean the appearance of each object only has one color and you want to record the (object name & color) pairs of all the objects in the scene?

**Comment by hpc100** [comment]
"It's exactly what I want to do—retrieve a color for each object name.

**Comment by hpc100** [comment]
Thank you very much for your response.

Indeed, my initial approach was to try to retrieve the color of the objects (but this seems quite complicated given the number of materials and colors). It might be better to rely on RGB images.

Thank you.
