### ISSUE TITLE
Is there any step that I haven't completed?

### ISSUE THREAD

**Issue by wmkai** [princeton-vl/infinigen#324]
I checked the crash_summaries.txt, it shows `09/16 07:14AM outputs/my_videos/377de2ca/logs/opengl_0_0_0001_0.err reason='Could not summarize cause, check outputs/my_videos/377de2ca/logs/opengl_0_0_0001_0.err' node=None fatal=True`

Then I checked opengl_0_0_0001_0.err, it shows
`/xxx/infinigen/outputs/my_videos/377de2ca/tmp/opengl_d150d739c7254720bbd00b9c48fcbd2d.sh: line 8: /xxx/infinigen/infinigen/datagen/customgt/build/customgt: No such file or directory`

Is there any step that I haven't completed?

**Comment by araistrick** [comment]
It appears you havent installed our opengl ground truth module. this could have happened if you chose the MINIMAL_INSTALL version of Installation.md. You will need to either remove `opengl_gt` from your command, or you can run `bash scripts/install/compile_opengl.sh` to compile it.
