### ISSUE TITLE
Every sub folder in the output folder represents a scene?

### ISSUE THREAD

**Issue by wmkai** [princeton-vl/infinigen#325]
Great work! I am new to this area and I have some questions:
When I'm generating the video, I see many sub folders in the output folder, does every sub folder in the output folder represent a scene? 
When I'm using this command to generate a video with 500 scenes, will there be 500 sub folders in the output dir?
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos --num_scenes 500 \
    --pipeline_config local_256GB monocular_video cuda_terrain opengl_gt \ 
    --cleanup big_files --warmup_sec 30000 --config trailer_video high_quality_terrain \
    --pipeline_overrides "iterate_scene_tasks.frame_range=[1,25]" LocalScheduleHandler.jobs_per_gpu=2
```
And finally, I need to look inside the frames_* folders to see the output images and combine them together into an mp4 using `python infinigen/tools/results/parse_video.py outputs/xxx`? This means that there are some images in each frames_* folder so that I need to combine these images in each frames_* folder into a short video, and then combine these short videos into a large video?

**Comment by araistrick** [comment]
Yes, each subfolder outputs/my_videos/XYZ represents a scene generated & rendered using seed=XYZ.

On the latest version, once rendering is completed, all the frames_XYZ folders should be aggregated into a single `frames` folder which will contain all the image/GT/metadata. I typically combine this together using a command like `ffmpeg -r 24 -pattern_type glob -i outputs/my_videos/*/frames/Image/camera_0/*.png" out.mp4`

**Comment by araistrick** [comment]
1.
 --num_scenes 500 means the program will attempt to create 500 scenes before stopping. Each scene will produce 1 video by default, since each scene has 1 camera by default. So you will end up with 500 scenes, except some will likely crash, in which case it will be less. You can have more cameras per scene if you want more videos per scene.

2. & 4. are not typical but im not able to debug from the information given. You would need to look into the underlying logs to see what jobs are running & what they are stuck on / attempting to do. 

RE "CPU only", the coarse/populate steps may indeed say "CPU" and no GPU found, but these are inherently CPU-only and wouldnt benefit from a GPU. The only cause for alarm would be if the renderjobs said they were running CPU-only, but I am not able to tell what log files you extracted the snippets from. 

3. is a bug, I will fix this shortly.

**Comment by wmkai** [comment]
> --num_scenes 500 means the program will attempt to create 500 scenes before stopping. Each scene will produce 1 video by default, since each scene has 1 camera by default. So you will end up with 500 scenes, except some will likely crash, in which case it will be less. You can have more cameras per scene if you want more videos per scene.
> 
> 2. & 4. are not typical but im not able to debug from the information given. You would need to look into the underlying logs to see what jobs are running & what they are stuck on / attempting to do.
> 
> RE "CPU only", the coarse/populate steps may indeed say "CPU" and no GPU found, but these are inherently CPU-only and wouldnt benefit from a GPU. The only cause for alarm would be if the renderjobs said they were running CPU-only, but I am not able to tell what log files you extracted the snippets from.
> 
> 3. is a bug, I will fix this shortly.

Hi, thank you for replying!

RE "The only cause for alarm would be if the renderjobs said they were running CPU-only, but I am not able to tell what log files you extracted the snippets from." 

I found this snippets from almost every xxx.err file, including `xxxxxxxxxxx_0_log.err, coarse.err, populate.err`
```
[03:39:31.634] [init] [INFO] | Available devices have types=['CPU']
[03:39:31.634] [init] [WARNING] | Render will use CPU-only, only found types=['CPU']
```

while in a xxxxxxxxxxx_0_log.err, it shows:
```
[17:42:50.702] [logging] [INFO] | [Render Frames]
[17:42:50.703] [init] [INFO] | Available devices have types=['OPTIX', 'CUDA', 'CPU']
[17:42:50.703] [init] [INFO] | Cycles will use use_device_type='OPTIX', len(use_devices)=1
[17:42:50.708] [logging] [INFO] | [Actual rendering]
[23:36:07.358] [logging] [INFO] | [Actual rendering] finished in 5:53:16.649441
[23:36:07.358] [logging] [INFO] | [Post Processing]
[23:36:09.039] [logging] [INFO] | [Post Processing] finished in 0:00:01.680770
[23:36:09.716] [render] [INFO] | rendering time: 21199.013272047043
[23:36:09.716] [logging] [INFO] | [Render Frames] finished in 5:53:19.013670
[23:36:09.716] [logging] [INFO] | [MAIN TOTAL] finished in 5:54:00.745493
```
in the last line of the corresponding xxxxxxxxxxx_0_log.out, it shows:
```
Saved: '/mlx_devbox/users/mingkai.wang/playground/infinigen/outputs/my_videos/4b9b3562/tmp/0008.png'
 Time: 44:34.67 (Saving: 00:00.14)
```
Does this mean that rendering takes too much time and GPU acceleration is not used?

**Comment by wmkai** [comment]
> Yes, each subfolder outputs/my_videos/XYZ represents a scene generated & rendered using seed=XYZ.是的，每个子文件夹outputs/my_videos/XYZ代表使用seed=XYZ生成和渲染的场景。
> 
> On the latest version, once rendering is completed, all the frames_XYZ folders should be aggregated into a single `frames` folder which will contain all the image/GT/metadata. I typically combine this together using a command like `ffmpeg -r 24 -pattern_type glob -i outputs/my_videos/*/frames/Image/camera_0/*.png" out.mp4`在最新版本中，一旦渲染完成，所有的frames_XYZ文件夹都应该聚合到一个单独的`frames`文件夹中，其中将包含所有图像/GT/元数据。我通常使用类似的命令将其组合在一起 `ffmpeg -r 24 -pattern_type glob -i outputs/my_videos/*/frames/Image/camera_0/*.png" out.mp4`

I tried this command and got a pink video:
![image](https://github.com/user-attachments/assets/1b7b4813-9e25-4e81-b4b1-e238789b289e)

**Comment by wmkai** [comment]
I found that when I ran
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos --num_scenes 200 --pipeline_config local_256GB monocular_video cuda_terrain --cleanup big_files --warmup_sec 60000 --config trailer_video high_quality_terrain
```
In the `coarse` stage, the `coarse.err` shows
```
[14:10:02.793] [acceleratesupport] [INFO] | No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[14:10:20.545] [smb_client] [WARNING] | SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
[14:10:20.607] [init] [INFO] | Converted seed='44c3ac43' to scene_seed=1153674307, parsed as hexadecimal
[14:10:20.707] [execute_tasks] [INFO] | infinigen version 1.8.1
[14:10:20.707] [execute_tasks] [INFO] | CUDA_VISIBLE_DEVICES=
[14:10:20.715] [logging] [INFO] | [MAIN TOTAL]
[14:10:20.719] [execute_tasks] [INFO] | Processing frames 1 through 192 inclusive
[14:10:20.926] [init] [INFO] | Available devices have types=['CPU']
[14:10:20.926] [init] [WARNING] | Render will use CPU-only, only found types=['CPU']
[14:10:21.021] [logging] [INFO] | [terrain]
[14:10:21.035] [logging] [INFO] | [Create terrain]
[14:10:21.035] [core] [INFO] | Terrain using only on the fly on_the_fly_asset_folder=PosixPath('/mlx_devbox/users/mingkai.wang/playground/infinigen/outputs/my_videos/44c3ac43/coarse/assets')
```
It only found **CPU** and use **CPU** for rendering. CUDA/OPTIX is not found for acceleration. However, I found that there are several commands in `outputs/44c3ac43/run_pipeline.sh`, I think the first command is used for coarse task:
```
nice -n 20 /root/miniconda3/envs/infinigen/bin/python -m infinigen_examples.generate_nature -- --output_folder /mlx_devbox/users/mingkai.wang/playground/infinigen/outputs/my_videos/44c3ac43/coarse --seed 44c3ac43 --task coarse --task_uniqname coarse -g cliff trailer_video high_quality_terrain -p LOG_DIR='/mlx_devbox/users/mingkai.wang/playground/infinigen/outputs/my_videos/44c3ac43/logs' execute_tasks.frame_range=[1, 192] execute_tasks.camera_id=[0, 0].
```

Then, I ran this command and got:
```
[02:18:16.566] [acceleratesupport] [INFO] | No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[02:18:19.939] [smb_client] [WARNING] | SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
[02:18:19.959] [init] [INFO] | Converted seed='44c3ac43' to scene_seed=1153674307, parsed as hexadecimal
[02:18:20.021] [execute_tasks] [INFO] | infinigen version 1.8.1
[02:18:20.022] [execute_tasks] [INFO] | CUDA_VISIBLE_DEVICES=None
[02:18:20.027] [logging] [INFO] | [MAIN TOTAL]
[02:18:20.029] [execute_tasks] [INFO] | Processing frames 1 through 192 inclusive
[02:18:20.258] [init] [INFO] | Available devices have types=['OPTIX', 'OPTIX', 'OPTIX', 'OPTIX', 'CUDA', 'CUDA', 'CUDA', 'CUDA', 'CPU']
[02:18:20.258] [init] [INFO] | Cycles will use use_device_type='OPTIX', len(use_devices)=4
[02:18:20.319] [logging] [INFO] | [terrain]
[02:18:20.322] [logging] [INFO] | [Create terrain]
[02:18:20.322] [core] [INFO] | Terrain using only on the fly on_the_fly_asset_folder=PosixPath('/mlx_devbox/users/mingkai.wang/playground/infinigen/outputs/my_videos/44c3ac43/coarse/assets')
```

This means infinigen can find **GPU** and use **OPTIX**. I don't know why `manage_jobs.py` is not working for GPUs. What is difference between running `manage_jobs.py` and directly executing commands in `run_pipeline.sh`?

**Comment by araistrick** [comment]
Very sorry for the issues.

I will dig further into this now. manage_jobs' submitit_emulator tries to assign jobs to separate GPUs using CUDA_VISIBLE_DEVICES but I think its possible we arent setting the GPU ids correctly for your environment.

Could you send me the result of running `nvidia-smi -L` on your machine?.

Could you also confirm whether setting `CUDA_VISIBLE_DEVICES=0` or `CUDA_VISIBLE_DEVICES=1` is valid for your machine? or does it have to be a long uuid as the visible device. 

You should also try printing the value of `",".join([str(i) for i in cuda_devices])` from `https://github.com/git/git/blob/master/ifninigen/datagen/util/submitit_emulator.py?plain=1#L80`

**Comment by wmkai** [comment]
> nvidia-smi -L

Thanks for your reply.

Sure. This is my result:
```
(infinigen) ➜  infinigen git:(main) ✗ nvidia-smi -L 
GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-a13de0ee-4a3f-ceb6-021c-af6d1686a15b)
GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-838f1416-ba21-0e70-f8a2-648583992b52)
GPU 2: Tesla V100-SXM2-32GB (UUID: GPU-dba2c0ad-779c-8e94-14f1-d4ea8f1a6d67)
GPU 3: Tesla V100-SXM2-32GB (UUID: GPU-1e57d9fc-a028-6775-1a52-9ca36eea66ee)
```

I will follow your instruction to check the outputs and update them in this comment.

**Comment by araistrick** [comment]
The best next steps would be printing the CUDA_VISIBLE_DEVICES as mentioned in 3. and 4. above, then checking whether it works if you manually run the run_pipeline.sh command with those same CUDA_VISIBLE_DEVICES. 

If it uses the GPU, then this would be surprising, since then the run_pipeline and manage_jobs versions are very similar but one is using and one is not. 

If it doesnt use the GPU, then this means it is some invalid setting of CUDA_VISIBLE_DEVICES causing the issue, since this would be the only distinction between the new run versus running the run_pipeline.sh by itself.

**Comment by wmkai** [comment]
> Very sorry for the issues.对于这些问题非常抱歉。
> 
> manage_jobs' submitit_emulator tries to assign jobs to separate GPUs using CUDA_VISIBLE_DEVICES but I think its possible we arent setting the GPU ids correctly for your environment.Manage_jobs的submit_emulator尝试使用CUDA_VISIBLE_DEVICES将作业分配给单独的GPU，但我认为我们可能没有为您的环境正确设置GPU ID。
> 
> 1. Could you send me the result of running `nvidia-smi -L` on your machine?.您能否将在您的计算机上运行`nvidia-smi -L`的结果发送给我？
> 2. Could you also confirm whether setting `CUDA_VISIBLE_DEVICES=0` or `CUDA_VISIBLE_DEVICES=1` is valid for your machine? or does it have to be a long uuid as the visible device. I believe our code always sets integers as IDs like this, not long string uuids.您还能否确认设置`CUDA_VISIBLE_DEVICES=0`或`CUDA_VISIBLE_DEVICES=1`对您的计算机是否有效？或者它是否必须是一个长 uuid 作为可见设备。我相信我们的代码总是将整数设置为这样的 ID，而不是长字符串 uuid。
> 3. You should also try printing the value of `",".join([str(i) for i in cuda_devices])` from submitit_emulator.py line 80您还应该尝试打印以下值 `",".join([str(i) for i in cuda_devices])` 来自submit_emulator.py第80行
> 4. Another useful check would be `print(os.environ["CUDA_VISIBLE_DEVICES"])` at the start of generate_nature.py, as this will reveal what setting the child job is recieving.另一个有用的检查是 `print(os.environ["CUDA_VISIBLE_DEVICES"])` 在generate_nature.py的开头，因为这将揭示子作业正在接收的设置。

I ran
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos_check \
--num_scenes 1 --pipeline_config local_256GB monocular_video cuda_terrain \
--cleanup big_files --warmup_sec 60000 --config trailer_video high_quality_terrain
```
and try to print the result in 3 and 4 got an empty string. It seems that the child job did not find my GPU. 
Then I manually set CUDA_VISIBLE_DEVICES=0,1 and ran
```
CUDA_VISIBLE_DEVICES=0,1 python -m infinigen.datagen.manage_jobs \
--output_folder outputs/my_videos_check --num_scenes 1 \
--pipeline_config local_256GB monocular_video cuda_terrain \
--cleanup big_files --warmup_sec 60000 --config trailer_video high_quality_terrain
```
but it still printed nothing.

**Comment by araistrick** [comment]
For what job step did it print nothing? Remember that using no GPU is intentional for coarse.err and populate.err etc. The informative thing would be if there is no gpu for rendershort.err

Other places to try debug would be printing the value of `gpu_assignment` in `LocalScheduleHandler.dispatch` and also print `n_gpus` in `attempt_dispatch_job`. Both of these should be empty/zero for coarse but have 1 gpu for render, otherwise something is wrong. 

Potentially a more efficient way for us to figure this out would be for me to add lots of logger.debug statements for you to enable with --debug and I can tell whats going on, but this would require implementation and I am not able to commit to doing it this week.

**Comment by wmkai** [comment]
> For what job step did it print nothing? Remember that using no GPU is intentional for coarse.err and populate.err etc. The informative thing would be if there is no gpu for rendershort.err对于哪个作业步骤它没有打印任何内容？请记住，对于粗略.err 和 populate.err 等来说，不使用 GPU 是有意的。如果没有用于 rendershort.err 的 GPU，则提供信息。
> 
> Other places to try debug would be printing the value of `gpu_assignment` in `LocalScheduleHandler.dispatch` and also print `n_gpus` in `attempt_dispatch_job`. Both of these should be empty/zero for coarse but have 1 gpu for render, otherwise something is wrong.其他尝试调试的地方是在`LocalScheduleHandler.dispatch`中打印`gpu_assignment`的值，并在`attempt_dispatch_job`中打印`n_gpus` 。对于粗略来说，这两个值都应该为空/零，但有 1 个 GPU 用于渲染，否则会出现问题。
> 
> Potentially a more efficient way for us to figure this out would be for me to add lots of logger.debug statements for you to enable with --debug and I can tell whats going on, but this would require implementation and I am not able to commit to doing it this week.对我们来说，解决这个问题的一个更有效的方法是我添加大量 logger.debug 语句，以便您使用 --debug 启用，我可以告诉发生了什么，但这需要实现，而我无法承诺本周就这样做。

Thank you so much for you reply!

1. I think the logs may have misled me. I found the following logs in the `coarse.err` and `populate.err` files:
```
[06:53:02.815] [init] [INFO] | Available devices have types=['CPU']
[06:53:02.815] [init] [WARNING] | Render will use CPU-only, only found types=['CPU']
```
I know it’s normal for the coarse and populate tasks not to use the GPU, but why does `Render will use CPU-only` appear in `coarse.err` and `populate.err` instead of something like `Coarse will use CPU-only` or `Populate will use CPU-only`? I think this log is misleading.

I found the following logs in `rendershort_xxxx.err` and `fineterrain.err`:
```
[15:12:47.730] [init] [INFO] | Available devices have types=['OPTIX', 'CUDA', 'CPU']
[15:12:47.730] [init] [INFO] | Cycles will use use_device_type='OPTIX', len(use_devices)=1
```
Can this indicate that my render and fineterrain processes are using GPU acceleration properly?

2. When I use `manage_jobs` to generate a large number of videos, according to the err logs, it seems that each task’s rendering process only uses 1 GPU, and it cannot use multi-GPU parallelism for a single video rendering task. However, when I use `generate_nature` to generate a single video, infinigen can use 4GPU to render a single video.
Is the former method faster than later method when I generate many videos?

3. I ran
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos_check \
--num_scenes 200 --pipeline_config local_256GB monocular_video cuda_terrain \
--cleanup big_files --warmup_sec 60000 --config trailer_video high_quality_terrain
--pipeline_overrides iterate_scene_tasks.frame_range=[1,192] \
```
on 4 V100 GPUs to generate a large number of videos, it took 3-4 days to generate just 3 videos at 192fps (8s). Is that normal? If not, could you please give me an estimated time to generate a 192fps (8s) video, so I can determine whether the process is running as expected?

Thank you so much! @araistrick

**Comment by araistrick** [comment]
Ah I see! Yes that error message is very misleading. I guess it is supposed to mean "if _this_ process does rendering then it will be cpu only", which can be the case for some jobs if --task has all of coarse fine render in one job. But I will correct it to be more clear or to only print if currently in a render job.

RE timing I generally get ~5-10min render time per frame at default settings, with the scene geometry complexity being the biggest factor. IE arctic scenes can be 1m, forests are usually 10m+. So if you assume that every GPU is always working on a render you can try to extrapolate the video/day throughput.

It's hard to check throughout is correct for specific hardware without inspecting a whole bunch of things, but if you check that every GPU always has a render job assigned and that render time falls in this range, then I'd say it is generally correct. 

You can get a lot more videos if you do less samples per pixel, lower resolution, or lower fps. But for the most part, ray tracing is quite expensive.

**Comment by wmkai** [comment]
> Ah I see! Yes that error message is very misleading. I guess it is supposed to mean "if _this_ process does rendering then it will be cpu only", which can be the case for some jobs if --task has all of coarse fine render in one job. But I will correct it to be more clear or to only print if currently in a render job.啊我明白了！是的，该错误消息非常具有误导性。我想这应该意味着“如果_这个_进程进行渲染，那么它将仅是CPU”，如果 --task 在一项作业中具有所有粗细渲染，则某些作业可能会出现这种情况。但我会将其更正为更清晰，或者仅在当前处于渲染作业时进行打印。
> 
> RE timing I generally get ~5-10min render time per frame at default settings, with the scene geometry complexity being the biggest factor. IE arctic scenes can be 1m, forests are usually 10m+. So if you assume that every GPU is always working on a render you can try to extrapolate the video/day throughput.RE 计时 在默认设置下，我通常每帧获得约 5-10 分钟的渲染时间，其中场景几何复杂性是最大的因素。 IE北极场景可以是1m，森林通常是10m+。因此，如果您假设每个 GPU 始终都在进行渲染，您可以尝试推断视频/天的吞吐量。
> 
> It's hard to check throughout is correct for specific hardware without inspecting a whole bunch of things, but if you check that every GPU always has a render job assigned and that render time falls in this range, then I'd say it is generally correct.如果不检查一大堆东西，就很难检查特定硬件的整个过程是否正确，但如果您检查每个 GPU 始终分配了渲染作业并且渲染时间落在这个范围内，那么我会说它通常是正确的。
> 
> You can get a lot more videos if you do less samples per pixel, lower resolution, or lower fps. But for the most part, ray tracing is quite expensive.如果每像素采样较少、分辨率较低或帧速率较低，您可以获得更多视频。但在大多数情况下，光线追踪非常昂贵。

Got it! Thank you!
