### ISSUE TITLE
More room with objects

### ISSUE THREAD

**Issue by hpc100** [princeton-vl/infinigen#326]
Hello,
Thank's for your work.

## Problems
I ran your command to generate indoor whole appartement, however I noticed that only one room contains objects (like you say in md file) (see illustration)

## Steps to Reproduce

`python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' LocalScheduleHandler.use_gpu=False manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True compose_indoors.terrain_enabled=False --overwrite`

## Figure
![Multiple_room_but_one_with_object](https://github.com/user-attachments/assets/d768203f-a23a-4d49-8314-1aba3d878510)

## Question
I would like to know which parameter I need to modify, if i want to place object in all rooms ? (compose_indoors ? or another parameter ?)

Thank's in advance.

**Comment by araistrick** [comment]
If you want multiple rooms to be solved with objects, you should remove `--configs singleroom.gin` from your command, as this causes us to only generate a layout for a single room

**Comment by GavinZhengOI** [comment]
Hi Araistrick @araistrick, I'm using the exact same config with `--configs singleroom.gin` and `--overrides compose_indoors.restrict_single_supported_roomtype=True` deleted. It runs for tens of hours and ultimately result in a crash.

Here are some info provided by `crash_summary`:
```
09/21 12:07AM outputs/video_multiroom_dataset/5db391c0/logs/coarse.err reason='AssertionError:  ' node=None fatal=True
09/21 04:21PM outputs/huge_dataset_nooverride/b69f95a/logs/coarse.err reason='ValueError:  Could not find 1 camera views' node=None fatal=True
09/22 08:33AM outputs/huge_dataset_nooverride/69c2b33d/logs/coarse.err reason='AssertionError:  ' node=None fatal=True
```

One of the example of `coarse.err`:
```
raise proxy.with_traceback(exception.__traceback__) from None  File "/home/gavinzheng/miniconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)  File "/home/gavinzheng/Documents/infinigen/infinigen/core/constraints/example_solver/annealing.py", line 207, in retry_attempt_proposals
    succeeded = move.apply(state)  File "/home/gavinzheng/Documents/infinigen/infinigen/core/constraints/example_solver/moves/addition.py", line 90, in apply
    assert target_name not in state.objsAssertionError: 
  In call to configurable 'retry_attempt_proposals' (<function SimulatedAnnealingSolver.retry_attempt_proposals at 0x74c67e3d7400>)
  In call to configurable 'solve_objects' (<function Solver.solve_objects at 0x74c67e3f6200>)
  In call to configurable 'compose_indoors' (<function compose_indoors at 0x74c67d835750>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x74c67dbe6a70>)
  ```
If I don't delete `--configs singleroom.gin` and `--overrides compose_indoors.restrict_single_supported_roomtype=True`, everything is working well. Could you provides some insight to this problem? Let me know if you need any other info. Thanks!

**Comment by hpc100** [comment]
@araistrick thank's for your answer. I run this command and it work well. However I noticed that for each scene, one room is alway empty. Do you have any idea ?
@GavinZhengOI do you noticed the same issue ?
Thank's.

**Comment by GavinZhengOI** [comment]
@hpc100 No I didn't notice this specific issue, my every attempt to generate a full room will result in a crash(#333 for more detail). Could you share what is the exact command you use? And how much RAM do you have? Thanks!

**Comment by hpc100** [comment]
I run this command 
`python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1000 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' LocalScheduleHandler.use_gpu=False manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.terrain_enabled=False --overwrite
`
with 188G RAM

**Comment by GavinZhengOI** [comment]
> I run this command `python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1000 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' LocalScheduleHandler.use_gpu=False manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.terrain_enabled=False --overwrite ` with 188G RAM

Got it. It seems like I didn't allocate enough memory. I'll switch to another server and have a try. Get back to you later.

**Comment by hpc100** [comment]
approx one day

**Comment by GavinZhengOI** [comment]
> @araistrick thank's for your answer. I run this command and it work well. However I noticed that for each scene, one room is alway empty. Do you have any idea ? @GavinZhengOI do you noticed the same issue ? ![Iamge2](https://private-user-images.githubusercontent.com/145356917/370631842-0bbdb3fe-e205-460c-8e72-6b1a59871d09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NDU3NTAsIm5iZiI6MTcyODk0NTQ1MCwicGF0aCI6Ii8xNDUzNTY5MTcvMzcwNjMxODQyLTBiYmRiM2ZlLWUyMDUtNDYwYy04ZTcyLTZiMWE1OTg3MWQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQyMjM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTc0ZTliMjFmYTliMDJmN2VkNDlkMWIwNDM3YjAzZmE1NjU3YzY4ZTg0Nzk5ZGU3YmIxNWY0OWZmMTYzOWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8N14difz0Zh0JIxK3qhZtervyLEYYKQiMK67-3toAzE) ![Image1](https://private-user-images.githubusercontent.com/145356917/370631852-862fb8a8-acfa-4b06-91d8-c8554d2a50ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NDU3NTAsIm5iZiI6MTcyODk0NTQ1MCwicGF0aCI6Ii8xNDUzNTY5MTcvMzcwNjMxODUyLTg2MmZiOGE4LWFjZmEtNGIwNi05MWQ4LWM4NTU0ZDJhNTBjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQyMjM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGNiYjFkYjJmY2QxY2VkNzJkNDMzYTQzYWYwOTJlZDVmMzkzMDFhM2YyZGE0YzhlMjdlYzQ4MTM4OGMxNzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h8QCq6lD7UMLiihgOsPoB1QrBQUJg2EVWkb6UPs2Ob0)
> 
> Thank's.

Hi, I checked my result, and there is indeed an empty room, but it’s a very small one. I suspect it might be a storage space.
![Screenshot from 2024-10-14 18-34-41](https://github.com/user-attachments/assets/b0a57d40-fbfb-4e44-bc70-131ff82ed366)

**Comment by hpc100** [comment]
Hi, thank's for your feedback. I also checked the empty room and noticed that it's often garage and hallway, it's might be normal.

**Comment by shepera** [comment]
> approx one day

May I ask if you generated 1 scene a day or 1000 scenes a day (which is implied by the command)?  I'm trying to generate some cases for testing with infiniGen, but I'm facing a quite long generation time. I'm trying to identify the reason. Thanks in advance.

**Comment by hpc100** [comment]
@shepera 1 some per day.
