### ISSUE TITLE
Error with using sample room command on ubuntu wsl - "FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

### ISSUE THREAD

**Issue by andytriboletti** [princeton-vl/infinigen#329]
# Describe the bug
I am on windows and when i ran the sample command I got an error.
### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

### What command did you run?
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --pipeline_overrides LocalScheduleHandler.use_gpu=False --overwrite

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.
Crashed: 09/19 12:37AM outputs/my_dataset/6059759c/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -v -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: 
- GPU (?) :
- GPU Driver Version (?) :
- RAM (GB):

# Additional context

**Comment by araistrick** [comment]
This appears to be the same underlying issue as #327: since there are two `--pipeline_overrides` fields in the command, the first one is being ignored & the system is defaulting to nature not indoors.
