### ISSUE TITLE
in ImplementingAssets.md, something is  error

### ISSUE THREAD

**Issue by hangpengjie** [princeton-vl/infinigen#331]
at this file https://github.com/princeton-vl/infinigen/blob/main/docs/ImplementingAssets.md

![image](https://github.com/user-attachments/assets/2d9f4dba-6d89-4c45-b2e6-a8e637126372)

What you mean should be 'infinigen' ?
ps: After debugging for a long time, finally discovered this error

**Comment by araistrick** [comment]
Thanks for catching and sorry for the error, this is fixed as of #308
