### ISSUE TITLE
generating indoor assets is still an issue

### ISSUE THREAD

**Issue by andytriboletti** [princeton-vl/infinigen#336]
It's still an issue. I couldn't reopen the bug you closed.

I ran
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --overwrite --pipeline_overrides LocalScheduleHandler.use_gpu=False

I got outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
Crashed: 09/27 10:42PM outputs/my_dataset/61725392/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

Full log:

(infinigen) andy@andys-pc:~/infinigen$ python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --overwrite --pipeline_overrides LocalScheduleHandler.use_gpu=False
Failed to open dir (No such file or directory): /run/user/1002/gvfs/
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:CUSTOMGT_PATH=PosixPath('/home/andy/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
Using get_slurm_banned_nodes()=[]
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 1
------------------------------------------------------------
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
Crashed: 09/27 10:42PM outputs/my_dataset/61725392/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------
(infinigen) andy@andys-pc:~/infinigen$

Running on ubuntu wsl

_Originally posted by @andytriboletti in https://github.com/princeton-vl/infinigen/issues/327#issuecomment-2380373164_

**Comment by araistrick** [comment]
Hello,

this command still features the same issue as before, it contains "--pipeline_overrides" twice, and therefore argparse is ignoring one of them and only applying the second one:

Your command, with the two --pipeline_overrides 
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin **--pipeline_overrides** get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --overwrite **--pipeline_overrides** LocalScheduleHandler.use_gpu=False
```

instead, combine them:
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin **--pipeline_overrides** get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True LocalScheduleHandler.use_gpu=False --overwrite
```

**Comment by andytriboletti** [comment]
this worked. thank you.
