### ISSUE TITLE
Run transpiler in blender

### ISSUE THREAD

**Issue by abolfazl-sh** [princeton-vl/infinigen#344]
# Describe the bug
I just try to run the transpiler_dev_script.py in blender scripting tab.
The out put of running script in blender is as follow:
```Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ModuleNotFoundError: No module named 'infinigen'
```
It seems the blender try to import the transpiler.py module, but it has some problem with the path.

### Platform
- OS & OS Version:  mac sonoma 14.5 (macbook air m1)
- GPU (?) : -
- GPU Driver Version (?) :  -
- RAM (GB): 8

**Comment by araistrick** [comment]
Have you completed the "Installing Infinigen as a Blender Python script" instructions including "INFINIGEN_MINIMAL_INSTALL=True bash scripts/install/interactive_blender.sh" ? 

the transpiler will only work inside a copy of blender which has infinigen installed, so you either have to use our interactive_blender.sh installer, or figure out how to pip install infinigen into your own copy of blender.

If this does not solve, please paste the full install logs from running interactive_blender.sh, and also paste the full import error message IE showing the full traceback of which modules imported what other modules.

**Comment by abolfazl-sh** [comment]
Well, I install the Infinigen as "Installing Infinigen as a Python Module". I replaced the Infinigen env with the Python of Blender and it worked. On the other hand, one of my friends suggested your point, and it worked too(for others in the future).
Thanks for your response.
