### ISSUE TITLE
Hello world is broken due to new landlab version

### ISSUE THREAD

**Issue by davshus** [princeton-vl/infinigen#351]
# Describe the bug

The outdoor hello world script fails on a new installation, with the following error:
```
File "/.../site-packages/numpy/core/arrayprint.py", line 1441, in dtype_is_implied
    if _format_options['legacy'] <= 113 and dtype.type == bool_:
TypeError: '<=' not supported between instances of 'str' and 'int'
```
I traced this error to an issue with the `landlab` package detailed here: https://github.com/landlab/landlab/issues/2018
This issue occurs when using `numpy<2` as required by `infinigen` and `landlab>=2.9.0` (according to the tags on [this commit](https://github.com/landlab/landlab/commit/efcfe47bc5fd68d006d124778b1979ee4bdae831)).
This error is resolved when I downgrade to `landlab==2.8.0`.

## Steps to Reproduce
1. Install infinigen with `numpy==1.26.4` and `landlab==2.9.1`.
2. Run `python -m infinigen_examples.generate_nature --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse` 

### What version of the code were you using? 
7105e2caf66f87b2384a459878ca1cd8b3e35c97

### What command did you run?
`python -m infinigen_examples.generate_nature --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse`

### What are your FULL output logs?
[logs.txt](https://github.com/user-attachments/files/17348903/logs.txt)

**Comment by araistrick** [comment]
Should be fixed, thanks for the report. We intend to only use landlab 2.6.0 for the timebeing.
