### ISSUE TITLE
Can't run HelloRoom.md (failing with TypeError )

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [princeton-vl/infinigen#353]
Any ideas on what could be the problem? 

```
/content/infinigen# python -m infinigen.datagen.manage_jobs \
    --output_folder outputs/my_dataset \
    --num_scenes 1 \
    --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin \
    --configs singleroom.gin \
    --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 LocalScheduleHandler.use_gpu=False \
    --overrides compose_indoors.restrict_single_supported_roomtype=True \
    --overwrite
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:CUSTOMGT_PATH=PosixPath('/content/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
Using get_slurm_banned_nodes()=[]
outputs/my_dataset 10/15 10:33PM -> 10/15 10:33PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.3
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 1
------------------------------------------------------------
outputs/my_dataset 10/15 10:33PM -> 10/15 10:33PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.3
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 10/15 10:33PM -> 10/15 10:33PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.3
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 10/15 10:33PM -> 10/15 10:33PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.3
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 10/15 10:33PM -> 10/15 10:33PM
Crashed: 10/15 10:33PM outputs/my_dataset/7aca7e66/logs/coarse.err reason="TypeError:  '<=' not supported between instances of 'str' and 'int'" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.3
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------
```

**Comment by David-Yan1** [comment]
Could you post the contents of the `coarse.err` file? Thanks!

**Comment by makolon** [comment]
In my case, `course.err` like this.

```
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/trimesh/grouping.py:15: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.0)
  from scipy.spatial import cKDTree
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/landlab/__init__.py:38: UserWarning: legacy printing option can currently only be '1.13', '1.21', or `False`
  np.set_printoptions(legacy="1.25")
Traceback (most recent call last):
  File "/root/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/infinigen/infinigen_examples/generate_indoors.py", line 24, in <module>
    from infinigen.assets.objects.wall_decorations.skirting_board import make_skirting_board
  File "/opt/infinigen/infinigen/assets/objects/wall_decorations/__init__.py", line 5, in <module>
    from .balloon import BalloonFactory
  File "/opt/infinigen/infinigen/assets/objects/wall_decorations/balloon.py", line 10, in <module>
    from infinigen.assets.scatters import clothes
  File "/opt/infinigen/infinigen/assets/scatters/clothes.py", line 12, in <module>
    from infinigen.assets.objects.clothes import blanket, pants, shirt
  File "/opt/infinigen/infinigen/assets/objects/clothes/__init__.py", line 8, in <module>
    from .towel import TowelFactory
  File "/opt/infinigen/infinigen/assets/objects/clothes/towel.py", line 13, in <module>
    from infinigen.assets.objects.elements.rug import ArtRug
  File "/opt/infinigen/infinigen/assets/objects/elements/__init__.py", line 1, in <module>
    from .doors import (
  File "/opt/infinigen/infinigen/assets/objects/elements/doors/__init__.py", line 12, in <module>
    from .casing import DoorCasingFactory
  File "/opt/infinigen/infinigen/assets/objects/elements/doors/casing.py", line 15, in <module>
    from infinigen.core.constraints.constraint_language.constants import RoomConstants
  File "/opt/infinigen/infinigen/core/constraints/constraint_language/__init__.py", line 20, in <module>
    from .gather import (
  File "/opt/infinigen/infinigen/core/constraints/constraint_language/gather.py", line 10, in <module>
    from .geometry import ObjectSetExpression
  File "/opt/infinigen/infinigen/core/constraints/constraint_language/geometry.py", line 20, in <module>
    class accessibility_cost(ScalarExpression):
  File "/opt/infinigen/infinigen/core/constraints/constraint_language/types.py", line 22, in decorator
    cls = ddec(cls)
  File "/root/miniconda3/envs/infinigen/lib/python3.10/dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/root/miniconda3/envs/infinigen/lib/python3.10/dataclasses.py", line 1093, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
  File "/root/miniconda3/envs/infinigen/lib/python3.10/inspect.py", line 3211, in __str__
    formatted = str(param)
  File "/root/miniconda3/envs/infinigen/lib/python3.10/inspect.py", line 2732, in __str__
    formatted = '{} = {}'.format(formatted, repr(self._default))
  File "/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1479, in _array_repr_implementation
    skipdtype = dtype_is_implied(arr.dtype) and arr.size > 0
  File "/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1429, in dtype_is_implied
    if _format_options['legacy'] <= 113 and dtype.type == bool_:
TypeError: '<=' not supported between instances of 'str' and 'int'
```

After troubleshooting, I resolved the issue by downgrading landlab to version 2.6.0. I hope this information helps if anyone encounters similar issues.

**Comment by deolipankaj** [comment]
> In my case, `course.err` like this.
> 
> ```
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
>   setattr(self, word, getattr(machar, word).flat[0])
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
>   return self._float_to_str(self.smallest_subnormal)
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/trimesh/grouping.py:15: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.0)
>   from scipy.spatial import cKDTree
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
>   setattr(self, word, getattr(machar, word).flat[0])
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
>   return self._float_to_str(self.smallest_subnormal)
> /root/miniconda3/envs/infinigen/lib/python3.10/site-packages/landlab/__init__.py:38: UserWarning: legacy printing option can currently only be '1.13', '1.21', or `False`
>   np.set_printoptions(legacy="1.25")
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/opt/infinigen/infinigen_examples/generate_indoors.py", line 24, in <module>
>     from infinigen.assets.objects.wall_decorations.skirting_board import make_skirting_board
>   File "/opt/infinigen/infinigen/assets/objects/wall_decorations/__init__.py", line 5, in <module>
>     from .balloon import BalloonFactory
>   File "/opt/infinigen/infinigen/assets/objects/wall_decorations/balloon.py", line 10, in <module>
>     from infinigen.assets.scatters import clothes
>   File "/opt/infinigen/infinigen/assets/scatters/clothes.py", line 12, in <module>
>     from infinigen.assets.objects.clothes import blanket, pants, shirt
>   File "/opt/infinigen/infinigen/assets/objects/clothes/__init__.py", line 8, in <module>
>     from .towel import TowelFactory
>   File "/opt/infinigen/infinigen/assets/objects/clothes/towel.py", line 13, in <module>
>     from infinigen.assets.objects.elements.rug import ArtRug
>   File "/opt/infinigen/infinigen/assets/objects/elements/__init__.py", line 1, in <module>
>     from .doors import (
>   File "/opt/infinigen/infinigen/assets/objects/elements/doors/__init__.py", line 12, in <module>
>     from .casing import DoorCasingFactory
>   File "/opt/infinigen/infinigen/assets/objects/elements/doors/casing.py", line 15, in <module>
>     from infinigen.core.constraints.constraint_language.constants import RoomConstants
>   File "/opt/infinigen/infinigen/core/constraints/constraint_language/__init__.py", line 20, in <module>
>     from .gather import (
>   File "/opt/infinigen/infinigen/core/constraints/constraint_language/gather.py", line 10, in <module>
>     from .geometry import ObjectSetExpression
>   File "/opt/infinigen/infinigen/core/constraints/constraint_language/geometry.py", line 20, in <module>
>     class accessibility_cost(ScalarExpression):
>   File "/opt/infinigen/infinigen/core/constraints/constraint_language/types.py", line 22, in decorator
>     cls = ddec(cls)
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/dataclasses.py", line 1175, in wrap
>     return _process_class(cls, init, repr, eq, order, unsafe_hash,
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/dataclasses.py", line 1093, in _process_class
>     str(inspect.signature(cls)).replace(' -> None', ''))
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/inspect.py", line 3211, in __str__
>     formatted = str(param)
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/inspect.py", line 2732, in __str__
>     formatted = '{} = {}'.format(formatted, repr(self._default))
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1479, in _array_repr_implementation
>     skipdtype = dtype_is_implied(arr.dtype) and arr.size > 0
>   File "/root/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/arrayprint.py", line 1429, in dtype_is_implied
>     if _format_options['legacy'] <= 113 and dtype.type == bool_:
> TypeError: '<=' not supported between instances of 'str' and 'int'
> ```
> 
> After troubleshooting, I resolved the issue by downgrading landlab to version 2.6.0. I hope this information helps if anyone encounters similar issues.

Thanks for this solution. It worked
