### ISSUE TITLE
EEVEE renderer?

### ISSUE THREAD

**Issue by Boltzmachine** [princeton-vl/infinigen#354]
Currently, infinigen uses Cycle as the renderer with 16000 samples. I took too long when generating a large number of scenes. I tried to switch to EEVEE but the rendered results are weird. Any suggestions?

**Comment by David-Yan1** [comment]
Currently, the system is not designed to support EEVEE rendering and it will break many materials and/or lighting. For higher render throughput, you can try turning down the number of samples (for indoor scenes, ~1000 would likely be sufficient) and using `configure_render_cycles.denoise=True`.
