### ISSUE TITLE
In HelloRoom, the automatical generation command will output a mixture of both indoor and outdoor scenes

### ISSUE THREAD

**Issue by Boltzmachine** [princeton-vl/infinigen#356]
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True 

```

This command will output a mixture of both indoor and outdoor scenes
<img width="1330" alt="Screenshot 2024-10-16 at 3 43 49 PM" src="https://github.com/user-attachments/assets/d2ebe7b6-45f4-4367-a8a0-c00f7431b2a8">

**Comment by David-Yan1** [comment]
Terrain generation is intended and enabled by default, in order to provide landscape outside the windows. It can be disabled with `compose_scene.terrain_enabled=False`
