### ISSUE TITLE
How can I generate a single object with infinigen? Such as chair or table.

### ISSUE THREAD

**Issue by HomesAmaranta** [princeton-vl/infinigen#358]
How can I generate a single object with infinigen? Such as chair or table.
And which feature set should I use? Minimal Install or Terrain (CPU)?
Thanks for your reply.

**Comment by GCChen97** [comment]
It's straightforward, for example:
```
from infinigen.assets.objects.seating.chairs import ChairFactory
ChairFactory(<RANDOM_SEED>).create_asset()
```
Remember to use `from ... import ...` rather than `import infinigen; infinigen..assets.objects.seating.chairs.ChairFactory`.

**Comment by araistrick** [comment]
The above answer works great from python, you can also follow our [GeneratingIndividualAssets documentation](https://github.com/princeton-vl/infinigen/blob/main/docs/GeneratingIndividualAssets.md) for a commandline version
