### ISSUE TITLE
Fail to generate chair seat

### ISSUE THREAD

**Issue by GCChen97** [princeton-vl/infinigen#359]
## Steps to Reproduce
In the console of the blender GUI, run the below codes:
```python
from infinigen.assets.objects.seating.chairs import ChairFactory
ChairFactory(6).create_asset()
```

### What version of the code were you using? 
```
commit 0fd9e541c351da4d49d62e902e827b5727e364ff (HEAD -> main, origin/main, origin/HEAD)
Merge: 9c3097a5 7c67fc00
Author: pvl-bot <bot@infinigen.org>
Date:   Fri Oct 18 17:00:00 2024 -0400
```

### What are your FULL output logs?
```
Info: Select two edge loops or a single closed edge loop from which two edge loops can be calculated
Warning: Unwrap failed to solve 12 of 12 island(s), edge seams may need to be added
```

### Platform
- OS & OS Version: Ubuntu 22.04

Below is the screenshot of two generated chairs with seeds 233 and 6. The one using 6 have no solid seat except a curve.
![chair](https://github.com/user-attachments/assets/15a8e220-4f55-4199-809f-546205016acb)

**Comment by araistrick** [comment]
Thanks for the report, this should be fixed in v1.10.1
