### ISSUE TITLE
Inconsistent behaviors of glass bsdf in bpy 3.6.0/4.0.0 vs 4.1.0

### ISSUE THREAD

**Issue by GCChen97** [princeton-vl/infinigen#368]
# Describe the bug
I was trying to add environment maps for the generated scenes and noticed that the windows show weird transmission of the env map.
Below are the rendered glass bsdf of blender 4.1.0 and blender 4.0.
![bpy4](https://github.com/user-attachments/assets/6dad297d-bf61-4fd2-9ee1-4af6c6c5a056)

## Steps to Reproduce
Generate a scene with windows and render.

### What version of the code were you using? 
Ver. 1.10.1

**Comment by GCChen97** [comment]
I tried bpy 4.2.0 and the rendered images of windows was correct.

**Comment by araistrick** [comment]
thanks for the report, we've updated to bpy==4.2.0 now so let me know if this is not resolved. 

our glass shader is quite complicated (IE, contains more tricks than just GlassBSDF) so its also possible its one of the other nodes fault.
