### ISSUE TITLE
Error when running HelloWorld with opengl_gt

### ISSUE THREAD

**Issue by Superviro** [princeton-vl/infinigen#374]
# Describe the bug
Following the instructions in GroundTruthAnnotations.md doc, I ran HelloWorld by replacing blender_gt.gin with opengl_gt.gin. But the process aborted with:
Error: /home/zzh/projects/infinigen/outputs/hello_world/0/0/savemesh_0_0_0048_0/frame_0048/mesh/static_saved_mesh_0023.npz does not exist.

### What version of the code were you using? 
v1.11.1

### What command did you run?
``python -m infinigen.datagen.manage_jobs --output_folder outputs/hello_world/0 --num_scenes 1 --specific_seed 0 \
--configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin opengl_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False``

### What are your FULL output logs?
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion failed: /home/zzh/projects/infinigen/infinigen/datagen/customgt/src/io.cpp (76)
Error: /home/zzh/projects/infinigen/outputs/hello_world/0/0/savemesh_0_0_0048_0/frame_0048/mesh/static_saved_mesh_0023.npz does not exist.

/home/zzh/projects/infinigen/outputs/hello_world/0/0/tmp/opengl_ddde60cb0aab4c02ba0a7a6993ee2163.sh: line 8: 3594104 Aborted                 (core dumped) /home/zzh/projects/infinigen/infinigen/datagen/customgt/build/customgt --input_dir /home/zzh/projects/infinigen/outputs/hello_world/0/0/savemesh_0_0_0048_0 --dst_input_dir /home/zzh/projects/infinigen/outputs/hello_world/0/0/savemesh_0_0_0048_0 --frame 48 --dst_frame 49 --output_dir /home/zzh/projects/infinigen/outputs/hello_world/0/0/frames_0_0_0048_0
```

I checked savemesh_0_0_0048_0.out, static_saved_mesh_0023.npz hasn't been stored in frame_0048/mesh as described.
Here's savemesh_0_0_0048_0.err and savemesh_0_0_0048_0.out: 
[42105391345_0_log.err.txt](https://github.com/user-attachments/files/17814868/42105391345_0_log.err.txt)
[42105391345_0_log.out.txt](https://github.com/user-attachments/files/17814870/42105391345_0_log.out.txt)

# Additional context
I also tried to replace blender_gt.gin with opengl_gt.gin for command that generates a quick test scene (indoor room with no furniture etc) with 5 multiview cameras in ConfiguringCameras.md, that is
``python -m infinigen.datagen.manage_jobs --output_folder outputs/mvs_test --num_scenes 1 --configs multiview_stereo.gin fast_solve.gin no_objects.gin --pipeline_configs local_256GB.gin monocular.gin opengl_gt.gin cuda_terrain.gin indoor_background_configs.gin --overrides camera.spawn_camera_rigs.n_camera_rigs=5 compose_nature.animate_cameras_enabled=False compose_indoors.restrict_single_supported_roomtype=True --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' iterate_scene_tasks.n_camera_rigs=5``

It output a similar error
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion failed: /home/zzh/projects/infinigen/infinigen/datagen/customgt/src/io.cpp (76)
Error: /home/zzh/projects/infinigen/outputs/mvs_test_OPENGL/38b5547a/savemesh_0_0_0048_0/frame_0048/mesh/static_saved_mesh_0001.npz does not exist.

/home/zzh/projects/infinigen/outputs/mvs_test_OPENGL/38b5547a/tmp/opengl_d3613ca43e38423d82e4051d6152e480.sh: line 8: 172241 Aborted                 (core dumped) /home/zzh/projects/infinigen/infinigen/datagen/customgt/build/customgt --input_dir /home/zzh/projects/infinigen/outputs/mvs_test_OPENGL/38b5547a/savemesh_0_0_0048_0 --dst_input_dir /home/zzh/projects/infinigen/outputs/mvs_test_OPENGL/38b5547a/savemesh_0_0_0048_0 --frame 48 --dst_frame 49 --output_dir /home/zzh/projects/infinigen/outputs/mvs_test_OPENGL/38b5547a/frames_0_0_0048_0
```

I wonder if it's related to issue #373?

**Comment by araistrick** [comment]
This should be fixed in v1.11.2, please pull main and let me know if not resolved.
