### ISSUE TITLE
Failed to initialize GLAD

### ISSUE THREAD

**Issue by Superviro** [princeton-vl/infinigen#379]
# Describe the bug
When running video generation for nature scenes, it crashes with error "Failed to initialize GLAD" in opengl log. I have compiled opengl with no error, and also can run HelloWorld(single frame) using opengl_gt. 

### What version of the code were you using? 
v1.11.2

### What command did you run?
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/video_smooth_nature --num_scenes 1 --pipeline_config monocular_video.gin local_128GB.gin cuda_terrain.gin opengl_gt.gin --configs high_quality_terrain --pipeline_overrides iterate_scene_tasks.cam_block_size=24
```

### What are your FULL output logs?
crash_summaries:
```
outputs/video_smooth_nature/61e42671/logs/opengl_0_0_0001_0.err reason='Could not summarize cause, check outputs/video_smooth_nature/61e42671/logs/opengl_0_0_0001_0.err' node=None fatal=True
```
opengl_0_0_0025_0.err:
```
Failed to initialize GLAD
```
And there's nothing in opengl_0_0_0025_0.out

**Comment by Superviro** [comment]
Fixed after adding display device

**Comment by geniuspatrick** [comment]
Hi, how to add display device? Do you mean a hardware?
