### ISSUE TITLE
Prompt to procedural generation code? possible?

### ISSUE THREAD

**Issue by chaiyuntian** [princeton-vl/infinigen#4]
You guys did a great work!
I don't know much about AI but I am recently learning procedural generation using blender's geometry node.
I am so excited to see this project and can't wait to see where it will be going.
I have this very naive idea: 
Since the the generation of the whole scene can be translated from node systems to code using Node Traspiler,
is it possible to : 
1 use the existing Geometry node library created by artists then translate it to code using Node Transplier and then 
2 pair the code labels such as name and desciptions/features.
3 Fine tune a LLM using the pair above
4 let the LLM generate the code and then excute the python code in blender to generate a random object/scene?

**Comment by araistrick** [comment]
By all means give it a try :)
