### ISSUE TITLE
Clarification Needed on --pipeline_configs Usage

### ISSUE THREAD

**Issue by 0xDCy** [princeton-vl/infinigen#47]
I've been trying to use  Infinigen with GPU acceleration by adding --pipeline_configs enable_gpu to my command, as instructed in the README. However, I've been encountering the following error:
```
blender: error: unrecognized arguments: --pipeline_configs enable_gpu
``` 
**Steps to Reproduce**
- What command did you run?
```
$BLENDER -noaudio --background --python generate.py -- --seed 13 --task coarse --g coast --output_folder outputs2/coarse2 --pipeline_configs enable_gpu
```

**Platform**
- OS & OS Version: WSL2 Ubuntu 22.04.2
- GPU (?) : Quadro p2000
- GPU Driver Version (?) :
- RAM (GB):

**Comment by bssrdf** [comment]
I think `--pipeline_configs enable_gpu` is supposed to be used with `tools.manage_datagen_jobs`, not `generate.py`

**Comment by 0xDCy** [comment]
> I think `--pipeline_configs enable_gpu` is supposed to be used with `tools.manage_datagen_jobs`, not `generate.py`

Believe you're correct. Hadn't seen that section when reading over earlier.
