### ISSUE TITLE
How can I use GPU acceleration？

### ISSUE THREAD

**Issue by luoluoluooo** [princeton-vl/infinigen#55]
My GPU is nvidia-RTX3090. I have already installed Cuda, and there is also a compilation package for Cuda when using ```install.sh```. And  also enabled on the command line to ```enable_GPU```, but when I render, the speed is still very slow, and the program in ```nvidia-smi``` does not occupy graphics memory.

![image](https://github.com/princeton-vl/infinigen/assets/58392618/2bb654ef-0070-4380-95cd-c9a9741f3ffb)

![image](https://github.com/princeton-vl/infinigen/assets/58392618/ede69fcb-918a-4aaf-9a4b-bb11f5abe126)

**Comment by David-Yan1** [comment]
Currently, `enable_GPU` only support CUDA acceleration for terrain, so there will only be active GPU usage during the terrain generation steps. However, we have been noticing an issue with terrain generation recently, such as in #53. Use `nvidia-smi` when specifically when running `fineterrain` to verify whether the GPU is properly accelerating terrain. If not, please post the generation logs so we can debug. It would also be helpful if you could check whether that the generated outputs have terrain. Thanks!

**Comment by luoluoluooo** [comment]
ok，i got it

**Comment by bssrdf** [comment]
Actually the render part of the code enabled GPUs, regardless of whether enable_gpu flag is passed.
```
# render/render.py
def enable_gpu(engine_name = 'CYCLES'):
    # from: https://github.com/DLR-RM/BlenderProc/blob/main/blenderproc/python/utility/Initializer.py
    compute_device_type = None
    prefs = bpy.context.preferences.addons['cycles'].preferences
    # Use cycles
    bpy.context.scene.render.engine = engine_name
    bpy.context.scene.cycles.device = 'GPU'

    preferences = bpy.context.preferences.addons['cycles'].preferences
    for device_type in preferences.get_device_types(bpy.context):
        preferences.get_devices_for_type(device_type[0])

    for gpu_type in ['OPTIX', 'CUDA']:#, 'METAL']:
        found = False
        for device in preferences.devices:
            if device.type == gpu_type and (compute_device_type is None or compute_device_type == gpu_type):
                bpy.context.preferences.addons['cycles'].preferences.compute_device_type = gpu_type
                logger.info('Device {} of type {} found and used.'.format(device.name, device.type))
                found = True
                break
        if found:
            break

    # make sure that all visible GPUs are used
    for device in prefs.devices:   
            device. Use = True
   
    return prefs.devices


def render_image(
    camera_id,
    min_samples,
    num_samples,
    time_limit,
    frames_folder,
    adaptive_threshold,
    exposure,
    passes_to_save,
    flat_shading,
    use_dof=False,
    dof_aperture_fstop=2.8,
    motion_blur=False,
    motion_blur_shutter=0.5,
    render_resolution_override=None,
    excludes=[],
):
    tic = time.time()

    camera_rig_id, subcam_id = camera_id

    for exclude in excludes:
        bpy.data.objects[exclude].hide_render = True

    with Timer(f"Enable GPU"):
        devices = enable_gpu()
```

If I use `tools/manage_datagen_jobs.py` to generate images, GPU/CUDA is not being used in rendering step.  
However, if I manually execute render step as listed in`run_pipeline.sh`, e.g.
```
nice -n 20 $BLENDER --background -y -noaudio --python generate.py -- --input_folder outputs/seaice6/0/fine_0_0_0048_0 --output_folder outputs/seaice6/0/frames_0_0_0048_0 --seed 0 --task render --task_uniqname short_0_0_0048_0 -g arctic intermediate -p render.render_image_func=@full/render_image LOG_DIR='outputs/seaice6/0/logs' execute_tasks.frame_range=[48,48] execute_tasks.camera_id=[0,0] execute_tasks.resample_idx=0
```
blender will use GPU and rendering is significantly faster (25 min on GTX 1070  vs. 4 hours on Intel i7 6700 3.4G)
I don't know why `tools/manage_datagen_jobs.py` is not working for GPUs. What is difference between running `tools/manage_datagen_jobs.py` and execute commands in `run_pipeline.sh`?

**Comment by cswiger** [comment]
Just starting with this project but one thing I've noticed - was researching why I am getting "skipping cuda" and found that 
the top install.sh script has for build terrain:

if [ -f "/usr/local/cuda/bin/nvcc" ]; then
    USE_CUDA=1 bash install_terrain.sh
else
    USE_CUDA=0 bash install_terrain.sh
fi

and I'm using Ubuntu 22.04 LTS, nvidia driver 530.41.03    CUDA Version: 12.1  with the package nvidia-cuda-toolkit 
that installs /usr/bin/nvcc

That package is not in the docker image so installing it now and will fix that in the script and test.

**Comment by WellTung666** [comment]
> My GPU is nvidia-RTX3090. I have already installed Cuda, and there is also a compilation package for Cuda when using `install.sh`. And also enabled on the command line to `enable_GPU`, but when I render, the speed is still very slow, and the program in `nvidia-smi` does not occupy graphics memory.
> 
> ![image](https://user-images.githubusercontent.com/58392618/248142571-2bb654ef-0070-4380-95cd-c9a9741f3ffb.png)
> 
> ![image](https://user-images.githubusercontent.com/58392618/248143115-ede69fcb-918a-4aaf-9a4b-bb11f5abe126.png)

I also have the same problem,how can i solved it.

**Comment by luoluoluooo** [comment]
> > My GPU is nvidia-RTX3090. I have already installed Cuda, and there is also a compilation package for Cuda when using `install.sh`. And also enabled on the command line to `enable_GPU`, but when I render, the speed is still very slow, and the program in `nvidia-smi` does not occupy graphics memory.
> > ![image](https://user-images.githubusercontent.com/58392618/248142571-2bb654ef-0070-4380-95cd-c9a9741f3ffb.png)
> > ![image](https://user-images.githubusercontent.com/58392618/248143115-ede69fcb-918a-4aaf-9a4b-bb11f5abe126.png)
> 
> I also have the same problem,how can i solved it.

Perhaps this is not a problem. In some stages, the program will use GPU acceleration, in other stage，the program is not。

**Comment by araistrick** [comment]
You should expect to see GPU usage briefly during the fine_terrain stage, and for a decent duration during any rendering stage. 0 GPU usage during coarse/populate stages is expected and typical. Confusion RE LocalScheduleHandler.use_gpu will be cleared up via PR
