### ISSUE TITLE
WSL install OK, but error "worldgen/terrain/lib/cpu/soil_machine/SoilMachine.so" 

### ISSUE THREAD

**Issue by mischaschaub** [princeton-vl/infinigen#6]
Am a proud first-time installer of infinigen under WSL on windows10 with a NVIDIA 3090.  Am nearly there, I hope, but got the attached error during my first run following your recommendation. Help would be highly welcome! Looking very much forward to using your fascinating approach!

[error.txt](https://github.com/princeton-vl/infinigen/files/11781269/error.txt)

**Comment by chienlungcheung** [comment]
I have encountered the same problem on ubuntu20.04, and it seems something went wrong when `bash install.sh`.

**Comment by yangcheng** [comment]
> I have encountered the same problem on ubuntu20.04, and it seems something went wrong when `bash install.sh`.

how did you resolve the issue?

**Comment by chienlungcheung** [comment]
Just found the way:

```bash
git clone https://github.com/g-truc/glm.git
cd glm
sudo cp -r glm /usr/local/include/
```
then `bash install.sh` again!

(the building depends on glm code, which is used for opengl.)

**Comment by mischaschaub** [comment]
Thanks, but our two problems seem to be different. I have had a perfect install, but it errors when I want to run it.

**Comment by maciekpoplawski** [comment]
> Just found the way:
> 
> ```shell
> git clone https://github.com/g-truc/glm.git
> cd glm
> sudo cp -r glm /usr/local/include/
> ```
> 
> then `bash install.sh` again!
> 
> (the building depends on glm code, which is used for opengl.)

This indeed fixes this problem. Thank you for help!

**Comment by mischaschaub** [comment]
OK, I did the recommended approach by maciekpoplawski, even a full reinstallation of everything, but now I just got another problem which I will open in another issue. This one is closed, many thanks!

**Comment by ykpercy** [comment]
> Just found the way:
> 
> ```shell
> git clone https://github.com/g-truc/glm.git
> cd glm
> sudo cp -r glm /usr/local/include/
> ```
> 
> then `bash install.sh` again!
> 
> (the building depends on glm code, which is used for opengl.)

thanks,this is good job!
however,another problem occurred.
`install.sh: line 108: ../../blender/3.3/python/bin/python3.10: Permission denied
/content/drive/MyDrive/infinigen/infinigen`
then complie interrupted
