### ISSUE TITLE
using enabled_gpu in docker container

### ISSUE THREAD

**Issue by timegate** [princeton-vl/infinigen#63]
I chose to run infinigen through a docker container on a public server since the vram of my personal computer does not exceed 12GB.

The below command works well
`python -m tools.manage_datagen_jobs --output_folder ./hello_world --num_scenes 1 --pipeline_configs local_16GB monocular opengl_gt --specific_seed 0 --configs desert simple`

But the below command throws cuda error
`python -m tools.manage_datagen_jobs --output_folder ./hello_world_gpu --num_scenes 1 --pipeline_configs local_16GB monocular opengl_gt enable_gpu --specific_seed 0 --configs desert simple`

`Crashed: 0 fineterrain_0_0_0048_0 66169506356  Error: Python: Traceback (most recent call last):,Error: /root/infinigen/worldgen/terrain/lib/cuda/elements/ground.so: cannot open shared object file: No such file or directory fatal=True 06/26 05:57AM`

I remembered there was a line "cuda skipping" when I installed through install.sh.
Does this current docker support cuda? or do you have any idea how to change docker to support cuda?

**Comment by tms-gvd** [comment]
Issue #53 suggests a docker image to use GPUs, yet it seems that it might fail to render some elements

**Comment by David-Yan1** [comment]
We recently overhauled the entire Docker workflow, please refer to the updated instructions for "Running Infinigen in a Docker Container", which include a new specific CUDA build for the Docker image. However, there is a known issue with `enable_gpu` causing terrain to disappear (`enable_gpu` really means enable CUDA terrain - we still use the GPU in other steps such as rendering regardless). If you want to use GPU for rendering but NOT terrain try adding `--pipeline_overrides LocalScheduleHandler.use_gpu=True` to the end of your command.

**Comment by timegate** [comment]
@David-Yan1 
Umm.. I did git clone infingen and tried make docker-build-cuda but it throws below errors.

```
docker build \
	--tag infinigen_docker_img \
	--progress auto \ci
unable to prepare context: path "ci" not found
Makefile:19: recipe for target 'docker-build-cuda' failed
make: *** [docker-build-cuda] Error 
```

I cannot make it what is \ci, could you please let me know what is it?, or is there any workaround?

**Comment by timegate** [comment]
@David-Yan1
The latest merge works well in a docker container on local computer, but for a docker container on server, the solution was a little bit tricky (because we cannot simply do xhost +local:docker).

```
make docker-build
make docker-setup
# make docker-run -> not working!
# docker_run.sh is written below
bash docker_run.sh
docker exec -it infinigen /bin/bash
conda activate infinigen
export DISPLAY=localhost:11.0 (maybe 10.0, or 12.0, or something else. maybe it's different everytime)
bash worldgen/tools/compile_opengl.sh
```

docker_run.sh (I referred https://stackoverflow.com/questions/48235040/run-x-application-in-a-docker-container-reliably-on-a-server-connected-via-ssh-w)
I merged contents in Makefile to existing make_docker.sh, but I would appreciate much if someone combine the following contents in to the current Makefile.
```
DOCKER_BUILD_PROGRESS=auto
DOCKER_TAG=infinigen_docker_img
PWD=./
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | sudo xauth -f $XAUTH nmerge -
sudo chmod 777 $XAUTH
X11PORT=`echo $DISPLAY | sed 's/^[^:]*:\([^\.]\+\).*/\1/'`
TCPPORT=`expr 6000 + $X11PORT`
sudo ufw allow from 172.17.0.0/16 to any port $TCPPORT proto tcp
DISPLAY=`echo $DISPLAY | sed 's/^[^:]*\(.*\)/172.17.0.1\1/'`

docker rm -f infinigen

docker run -td --privileged --net=host --ipc=host \
        --name="infinigen" \
        --gpus=all \
        --env NVIDIA_DISABLE_REQUIRE=1 \
        -e "BLENDER=/opt/infinigen/blender/blender" \
        -e "DISPLAY=$DISPLAY" \
        -e "QT_X11_NO_MITSHM=1" \
        -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
        -v $PWD/worldgen/outputs:/opt/infinigen/worldgen/outputs \
        -e "XAUTHORITY=$XAUTH" \
        -v $XAUTH:$XAUTH \
        -e ROS_IP=127.0.0.1 \
        --cap-add=SYS_PTRACE \
        -v /etc/group:/etc/group:ro \
        $DOCKER_TAG /bin/bash \
|| docker run -td --privileged --net=host --ipc=host \
        --name="infinigen" \
        --device /dev/dri \
        -e "BLENDER=/opt/infinigen/blender/blender" \
        -e "DISPLAY=$DISPLAY" \
        -e "QT_X11_NO_MITSHM=1" \
        -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
        -v $PWD/worldgen/outputs:/opt/infinigen/worldgen/outputs \
        -e "XAUTHORITY=$XAUTH" \
        -v $XAUTH:$XAUTH \
        -e ROS_IP=127.0.0.1 \
        --cap-add=SYS_PTRACE \
        -v /etc/group:/etc/group:ro \
        "$DOCKER_TAG" bash
```

```
python -m tools.manage_datagen_jobs --output_folder./hello_world --num_scenes 1 --specific_seed 0 --configs desert simple --pipeline_configs local_16GB monocular opengl_gt --pipeline_overrides LocalScheduleHandler.use_gpu=True

python -m tools.manage_datagen_jobs --output_folder ./hello_world2 --num_scenes 1 --specific_seed 0 --configs desert simple --pipeline_configs enable_gpu monocular 
```
![Image_0048_00_00](https://github.com/princeton-vl/infinigen/assets/16134605/f05b6313-c367-4c7c-85b7-4cfdf3012d52)
![Image_0048_00_00](https://github.com/princeton-vl/infinigen/assets/16134605/e4df8b0d-bd5c-4a94-8b87-c2d1e56ea4c7)

after following above pipelines, I could get reasonable results. but there's one weird thing - I turned on nvidia-smi and kept watching, but it didn't seem to be using the gpu. Do you know what did I missed?

**Comment by David-Yan1** [comment]
Just to make sure, there was no GPU usage at all reported by `nvidia-smi`? It is normal to have no GPU usage during the coarse and populate stages. For the first example command, the only GPU usage will be during the rendering stages at the end since CUDA terrain is off. Could you also check whether "/usr/local/cuda/bin/nvcc" exists in the   Docker?

**Comment by timegate** [comment]
@David-Yan1 
`python -m tools.manage_datagen_jobs --output_folder ./output/vid_10_complex --num_scenes 10 --configs under_water --pipeline_configs local_16GB monocular_video opengl_gt --pipeline_overrides LocalScheduleHandler.use_gpu=True`
after launching above command on 3090gpu * 8 server, I met `Unable to determine the device handle for GPU 0000:3F:00.0: Unknown Error` (though I'm not 100% sure it is caused by the command).
I'll check it (including what you let me know) as soon as this server is restored. Thanks so much everytime anyway :)

**Comment by araistrick** [comment]
Let us know if you weren't able to resolve the remaining 'Unable to determine the device handle' issue, I would imagine this is a driver / environment issue but let us know if we can help in any way.
