### ISSUE TITLE
Is there already generated annotated data available for download?

### ISSUE THREAD

**Issue by ZachL1** [princeton-vl/infinigen#64]
Hi, thank you for your great work!
Do you provide already generated annotated data for download?

**Comment by araistrick** [comment]
Hello, there is no pregenerated data yet but we know this is important and it is coming as soon as possible. We intend to continuously upload and release new data. We will post a roadmap , with timelines as for what to expect, in the coming days.

**Comment by araistrick** [comment]
Timeline for pre-generated data has been added to the roadmap
