### ISSUE TITLE
[BUG] infinigen.org has default opengraph params set

### ISSUE THREAD

**Issue by nickls** [princeton-vl/infinigen#70]
**Describe the bug**
Incorrect open graph parameters on infinigen.org cause issues when sharing (to twitter, etc.) or airdrop properly.

It opens this page:
https://your-docusaurus-test-site.com/

<img width="895" alt="image" src="https://github.com/princeton-vl/infinigen/assets/363928/c10d950d-3908-49b4-acfe-be1e607b559d">

**Comment by lahavlipson** [comment]
Thanks for catching this! It's now fixed.
