### ISSUE TITLE
❓World scale (mini-worlds)

### ISSUE THREAD

**Issue by escoolioinglesias** [princeton-vl/infinigen#71]
Hello,

I've been exploring the Infinigen project and I'm really impressed with the work you've done. I'm interested in generating smaller worlds for a project I'm working on, but I've noticed that the size of the generated world isn't directly configurable through a command-line argument or a configuration file.

I understand that the world generation process is determined by the algorithms and parameters set within the Python scripts themselves. I'm considering modifying these scripts to achieve my goal, but I wanted to reach out first to see if you have any guidance or recommendations.

Could you provide any insights on how I might go about scaling down the world size? Are there specific scripts or parameters I should focus on? I understand that altering the world size might affect other aspects of the world generation, so any advice you could provide would be greatly appreciated.

Thank you for your time and for the great work you've done on this project.

Cheers!

**Comment by mazeyu** [comment]
Hi,
the coarse world is finite (within a bounding box), while the next few steps extend the terrain into far away with cost O(log(scale)). May I ask what is the purpose of a small-scale world as this is not the best way to reduce cost (lmk if you need some way to reduce cost). Anyway, one way to achieve this is to set through gin the bounding_box variable in this function https://github.com/princeton-vl/infinigen/blob/5e66102df768273414c5e92fa99aa6476c17272a/worldgen/terrain/mesher/spherical_mesher.py#L19

**Comment by mazeyu** [comment]
also, modify through gin "UniformMesher.dimensions" to change the size of the coarse world (i.e., terrain + assets). The previous comment answers how to extend the terrain in later steps (while assets not being extended).

**Comment by escoolioinglesias** [comment]
Hi @mazeyu,

Thank you for your response and valuable insights! I appreciate your guidance.

I understand that reducing the world size may not be the most efficient way to address cost concerns, and I would be grateful for any additional suggestions you have to optimize the generation process. However, in my specific case, the generation cost itself is not a significant issue.

My main challenge lies in rendering video scenes within the generated world. While the world generation process performs well, I tried rendering a video scene and it was virtually impossible due to rendering time per frame.

Nevertheless, your suggestions to modify the bounding_box variable in the kernel_caller function and the "UniformMesher.dimensions" parameter are incredibly helpful. I will dig into the code and experiment with these adjustments to generate a smaller-scale world that is suitable for my project.

Once again, thank you for your time and your assistance, it's greatly appreciated!

**Comment by escoolioinglesias** [comment]
I tried some modifications as shown below, but I think I'm off the mark. The world is still enormous and rendering a single frame takes from 16minutes to 5 hours (512 samples to 4096).

uniform_mesher.py
```
@gin.configurable
class UniformMesher:
    def __init__(self,
        dimensions=(-2, 2, -2, 2, -2, 2), #modified these dimensions 
        subdivisions=(64, -1, -1), # -1 means automatic
        upscale=3,
        enclosed=False,
        bisection_iters=10,
        device="cpu",
        verbose=False,
    ):
```

spherical_mesher.py
```
@gin.configurable
def kernel_caller(kernels, XYZ, r_bound_max=None, cam_loc=None, bounding_box=None):
    sdfs = []
    for kernel in kernels:
        ret = kernel(XYZ, sdf_only=1)
        sdf = ret[Vars.SDF]
        if r_bound_max is not None:
            R = np.linalg.norm(XYZ - cam_loc, axis=-1)
            mask = R / r_bound_max - 1
            sdf = np.maximum(sdf, mask * magnifier)
        if bounding_box is not None:
            # Modified these values 
            x_min, x_max, y_min, y_max, z_min, z_max = (-2, 2, -2, 2, -2, 2)
            out_bound = (XYZ[:, 0] < x_min) | (XYZ[:, 0] > x_max) \
                | (XYZ[:, 1] < y_min) | (XYZ[:, 1] > y_max) \
                | (XYZ[:, 2] < z_min) | (XYZ[:, 2] > z_max)
            sdf[out_bound] = 1e6
        sdfs.append(sdf)
    ret = np.stack(sdfs, -1)
    return ret
```

**Comment by araistrick** [comment]
Its still likely very possible to make it run/render faster. Terrain is only one aspect - you can also increase `-p target_face_size.global_multiplier=10` to make the non-terrain assets lower-res. 

But ultimately yes the project does not render in even remotely close to real time. You may have some success getting fast performance with single assets (ive had some pretty single-asset scenes take <1m per frame, about as fast as you could expect from CYCLES), or using blender's EEVEE renderer (very untested, not likely to work off the bat). We are always looking to improve performance and will keep you updated. Realtime performance will probably require porting to some kind of game engine. Thanks for your interest in the project, follow up if you have other thoughts.
