### ISSUE TITLE
How to open the scene in blneder?

### ISSUE THREAD

**Issue by carlosedubarreto** [princeton-vl/infinigen#73]
I've  generated the scene but when opening the files in blender I see a terrain and a lot fo boxes.

I tried in many ways, buty I could not see the scene correctly, can you give some some orientation of what to do to see it in blender the way that is rendered using the script?

**Comment by carlosedubarreto** [comment]
Sorry for that, I saw that it will only show when I render using the "fine" scene.blend file
![image](https://github.com/princeton-vl/infinigen/assets/4061130/466f5769-85b5-4faa-ab41-4f60ebb67aca)

**Comment by carlosedubarreto** [comment]
Sorry, when I went to render other views I saw that even in "fine", I still have lots of boxes.
How to change then to actual mesh, as I think they are only place holders

![image](https://github.com/princeton-vl/infinigen/assets/4061130/ee8e60aa-49e5-42b5-b754-86bd2588ae7a)

I'm using these commands

# Generate a scene layout
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse

# Populate unique assets
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task populate fine_terrain -g desert simple --input_folder outputs/helloworld/coarse --output_folder outputs/helloworld/fine

**Comment by carlosedubarreto** [comment]
Thanks a lot, I see that I can configura this dist_cull and vis_cull on the gin config files, or I can set then by default at the worldgen/placement/placement.py on the populate_all function.

That is great, thanks

**Comment by JohnZhan2023** [comment]
> Sorry for that, I saw that it will only show when I render using the "fine" scene.blend file ![image](https://github.com/princeton-vl/infinigen/assets/4061130/466f5769-85b5-4faa-ab41-4f60ebb67aca)

I wonder how you render the one view using the "fine" scene.blend file, my result still contains boxes
