### ISSUE TITLE
Small typo in stereo_video.gin

### ISSUE THREAD

**Issue by tms-gvd** [princeton-vl/infinigen#76]
Hi,
Thanks for your very valuable work. I noticed a typo in `worldgen/tools/pipeline_configs/stereo_video.gin` on line 1:
`include 'tools/pipeline_config/monocular_video.gin'` whereas it should be `include 'tools/pipeline_configs/monocular_video.gin'` (missing s at pipeline_config)

**Comment by araistrick** [comment]
Good catch, feel free to submit a PR if you'd like contributor credit, otherwise ill patch this in tommorow night.
