### ISSUE TITLE
How generate a video?

### ISSUE THREAD

**Issue by yfq512** [princeton-vl/infinigen#77]
I run the code
```
python -m tools.manage_datagen_jobs --output_folder outputs/hello_world2 --num_scenes 1 --specific_seed 0 --configs desert simple --pipeline_configs local_16GB monocular_video blender_gt --pipeline_overrides LocalScheduleHandler.use_gpu=True
```
and outputs/hello_world2/jobs.log shows that program completed and stopped after 5 hours. 
> I get a lots file:
![11WX20230630-170621@2x](https://github.com/princeton-vl/infinigen/assets/52442277/3818de84-ba46-43fe-8014-2f720ce10f01)

But I can't find any video file in outputs/hello_world2 directory. Can you help me?

**Comment by araistrick** [comment]
You should be able to look inside the frames_* folders to see the output images that make up your video, and you can combine them together into an mpr using 'python tools/results/parse_video.py outputs/hello_world2'
