### ISSUE TITLE
Why the rendered RGB image suffer from obvious noise?

### ISSUE THREAD

**Issue by ewrfcas** [princeton-vl/infinigen#78]
Hi, thanks for your great work!

I have tried the demo pipeline and achieved the monocular RGB image/depth pair as follow.

![image](https://github.com/princeton-vl/infinigen/assets/12042259/826af1cd-8fbc-405b-b990-76d3e0ac2706)

I am curious why the quality of rendered RGB image is poor, which suffers from obvious noise in the image.
![image](https://github.com/princeton-vl/infinigen/assets/12042259/54d7e64d-7310-4426-827e-c3cd90683d41)

Maybe some settings are incorrect.

**Comment by araistrick** [comment]
Hello! Yes we set the raytracing samples pretty low in simple.gin to make it run fast in the hello world even if you do cpu rendering. For actual usage we expect people not to use 'simple' in their commands and to use a gpu to make rendering still fast.

**Comment by AtalsZem** [comment]
Maybe the 'use_denoised' parameter is not set [here](https://github.com/princeton-vl/infinigen/blob/f26a82e0ae5fc0b08a7d2d0cff6b9830e41d2d8f/worldgen/rendering/render.py#L281C59-L281C59), so the saved image is 'image_noisy'.
