### ISSUE TITLE
[BUG] blendergt killed because of memory usage

### ISSUE THREAD

**Issue by tms-gvd** [princeton-vl/infinigen#79]
**Describe the bug**
RAM memory is overloaded at step `Scene, ViewLayer | Updating Lights | Computing distribution` during render task with blender_gt

**Steps to Reproduce**
- What version of the code were you using?
```
commit 2c51a18971b07fa4b78d7b70af8a64709545ffa7
```

- What command did you run?
```
python -m tools.manage_datagen_jobs --output_folder outputs/forest_stereo_trial4 --num_scenes 1 --specific_seed 10 --configs forest simple --pipeline_configs local_16GB cuda_terrain stereo_1h_jobs blender_gt
```

- What are your output logs?
```
crashed.text
10 blendergt_0_0_0001_0 98889485661  unknown cause fatal=True 06/30 10:17AM
10 blendergt_0_0_0001_1 97375803090  unknown cause fatal=True 06/30 10:19AM
```
Output logs for both tasks are in enclosed files below.

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**
I run Infinigen in a Docker Container with CUDA and OpenGL, enclosed the output of `bash install.sh`

**Platform**
- OS & OS Version:
Ubuntu Server 18.04.6 LTS
- GPU (?) : NVIDIA TITAN RTX *2
- GPU Driver Version (?) : Driver Version: 530.30.02
- RAM (GB): 64

**Additional context**
The memory usage increases from 14-15GB as mentioned in the logs to max capacity. I ran again the command
```
nice -n 20 /opt/infinigen/blender/blender --background -y -noaudio --python generate.py -- --input_folder outputs/forest_stereo_trial4/10/fine --output_folder outputs/forest_stereo_trial4/10/frames_0_0_0001_0 --seed 10 --task render --task_uniqname blendergt_0_0_0001_0 -g forest simple -p render.render_image_func=@flat/render_image LOG_DIR='outputs/forest_stereo_trial4/10/logs' execute_tasks.frame_range=[1,1] execute_tasks.camera_id=[0,0] execute_tasks.resample_idx=0
```
and got the same error. Note that for the second task "blendergt_0_0_0001_", the error happened few steps after but the problem is the same, peak memory shows that memory is full hence the crash.

I noticed this problem at the exact same step on my local computer that has 32GB RAM.

I am trying other configurations (no CUDA, no OpenGL), I'll keep you updated.

[98889485661_0_log.err.txt](https://github.com/princeton-vl/infinigen/files/11916288/98889485661_0_log.err.txt)
[98889485661_0_log.out.txt](https://github.com/princeton-vl/infinigen/files/11916289/98889485661_0_log.out.txt)
[97375803090_0_log.err.txt](https://github.com/princeton-vl/infinigen/files/11916305/97375803090_0_log.err.txt)
[97375803090_0_log.out.txt](https://github.com/princeton-vl/infinigen/files/11916306/97375803090_0_log.out.txt)
[install_log.txt](https://github.com/princeton-vl/infinigen/files/11916640/install_log.txt)

**Comment by tms-gvd** [comment]
also, there is a typo in `stereo_1h_jobs` on line 8: `{'name': "fine_terrain", 'func': @queue_fine_terrain},` as it should be `{'name': "fineterrain", 'func': @queue_fine_terrain},` otherwise it raises the error:
https://github.com/princeton-vl/infinigen/blob/2c51a18971b07fa4b78d7b70af8a64709545ffa7/worldgen/tools/manage_datagen_jobs.py#L678

**Comment by araistrick** [comment]
I will close this for now due to inactivity, I merged your typochanges and credited you as a coauthor & by name in the commit. we are working on changes that will reduce overall memory usage significantly and should resolve this issue.

**Comment by tms-gvd** [comment]
Thanks a lot, I can't wait to work again on this great project
