### ISSUE TITLE
blender quit, no "/infinigen/worldgen/terrain/lib/cpu/soil_machine/SoilMachine.so: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by yangcheng** [princeton-vl/infinigen#8]
I followed readme to run 

```
 $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse --debug
```

```
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
[04:33:20.591] [root] [INFO] [core.py:343] | Converted args.seed='0' to scene_seed=0, parsed as hexadecimal
[04:33:20.618] [root] [INFO] [core.py:413] | infinigen version 1.0.0
[04:33:20.619] [root] [INFO] [core.py:414] | CUDA_VISIBLE_DEVICES=None
[04:33:20.619] [times] [INFO] [logging.py:35] | [MAIN TOTAL]
[04:33:20.624] [root] [INFO] [core.py:254] | Processing frames 1 through 1 inclusive
[04:33:20.632] [times] [INFO] [logging.py:35] | [Create terrain]
[04:33:20.632] [root] [INFO] [core.py:76] | Terrain using only on the fly on_the_fly_asset_folder=PosixPath('/home/cheng/play/infinigen/worldgen/outputs/helloworld/coarse/assets')

```

then it failed with 

```
OSError: /home/cheng/play/infinigen/worldgen/terrain/lib/cpu/soil_machine/SoilMachine.so: cannot open shared object file: No such file or directory
  In call to configurable 'run_erosion' (<function run_erosion at 0x7f228ca5eb00>)
  In call to configurable 'load_assets' (<function LandTiles.load_assets at 0x7f228865a8c0>)
  In call to configurable 'LandTiles' (<class 'terrain.elements.landtiles.LandTiles'>)
  In call to configurable 'scene' (<function scene at 0x7f23987cd360>)
  In call to configurable 'Terrain' (<class 'terrain.core.Terrain'>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f2287e37250>)

Blender quit
```

I checked the directory there is no SoilMachine.so file. 

also blender said , **CUDA_VISIBLE_DEVICES=None** , does it mean it's not use my GPU [ RTX-2080 ]? could this be related? 

System Info:
uname -a
`Linux x10 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
nvidia-smi
```

Sun Jun 18 04:36:54 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:81:00.0  On |                  N/A |
|  0%   45C    P8    23W / 250W |     37MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1682      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

```

Really appreciate any help

Thanks

**Comment by maciekpoplawski** [comment]
Same here. Just tried to run batch job and ended up with the same missing file. 
![image](https://github.com/princeton-vl/infinigen/assets/54249329/a5ef2920-5e58-4559-b096-1d0b1ac446a9)

**Comment by maciekpoplawski** [comment]
OH! I've found a clue!
![image](https://github.com/princeton-vl/infinigen/assets/54249329/6e8652c6-3d90-4f6e-9f67-6d586af4f648)

**Comment by chienlungcheung** [comment]
I have resolved it, [click me](https://github.com/princeton-vl/infinigen/issues/6#issuecomment-1596123061)

**Comment by maciekpoplawski** [comment]
Correct. I also resolved the issue.

**Comment by araistrick** [comment]
Hello all! Could one or more of you post the logs from running 'install.sh'? It seems compilation is not succeeding on your platform, and the logs would help us debug this

**Comment by yangcheng** [comment]
> Hello all! Could one or more of you post the logs from running 'install.sh'? It seems compilation is not succeeding on your platform, and the logs would help us debug this
I copied from console so may have some line break issues. 

[install.log](https://github.com/princeton-vl/infinigen/files/11783642/install.log)

**Comment by yangcheng** [comment]
> Hello all! Could one or more of you post the logs from running 'install.sh'? It seems compilation is not succeeding on your platform, and the logs would help us debug this

Please check the attachment, I copied from console so may have some line break issues.
[install.log](https://github.com/princeton-vl/infinigen/files/11783650/install.log)

**Comment by stallboy** [comment]
I have the same problem. after a second check, here is what I found.
the reason was my network CANNOT access git://. ( in .gitmodules file)
so the solution is: change the git:// to https:// in .gitmodules file. then:

git submodules deinit --all -f
bash install.sh

**Comment by aplatyps** [comment]
I have this issue as well when running on Linux. For some reason the GLM library cannot be linked so I resolved it by editing the `install_terrain.sh` file to link the path to GLM when compiling the soil_machine files (e.g. -I/~/infinigen/process_mesh/dependencies/glm) then run the following:
```bash
cd infinigen/worldgen/terrain/
USE_CUDA=0 bash install_terrain.sh
```
Hope it helps anyone else who is stuck.

**Comment by PriNova** [comment]
By installing with `sudo apt install libglm-dev` solved the linkage error.

**Comment by laxlyezhi** [comment]
> 

it works for me

**Comment by yangcheng** [comment]
> By installing with `sudo apt install libglm-dev` solved the linkage error.

cool! this solved the issue without code change

**Comment by PriNova** [comment]
> > By installing with `sudo apt install libglm-dev` solved the linkage error.
> 
> cool! this solved the issue without code change

Yes, but should be pointed out in the README of this porject.
