### ISSUE TITLE
[BUG] when I use LocalScheduleHandler.use_gpu=True, but the gpu is not used

### ISSUE THREAD

**Issue by zhangguochang** [princeton-vl/infinigen#87]
How to use gpu to generate?

**Comment by araistrick** [comment]
Hello, do your logs say that the GPU is detected during the render step? If so then the system is likely functioning normally, the only steps that use GPU are rendering and sometimes terrain if you use the 'cuda_terrain' config. Much of the time then gpu is idle, so we reccomend running  many scenes in parallel if you have enough RAM, as this will mean one scene is usually using the GPU

**Comment by araistrick** [comment]
https://github.com/princeton-vl/infinigen/blob/main/docs/ConfiguringInfinigen.md now has detailed info about configuring infinigen to use a gpu
