### ISSUE TITLE
animation rigs is correct only on fish

### ISSUE THREAD

**Issue by JiazheZhang** [princeton-vl/infinigen#89]
Hi, after I change the code, I tested the function of join_and_rig_parts. 
(I add 'self.animation_mode="run"' on the line 209 in worldgen\assets\creatures\genomes\herbivore.py)
I found that the animation rigs is correct only on fish, while rigging on other animals can lead to distortion of the model. 
I wonder the root cause, and I'd like to know if you will make optimizations in the future?

**Comment by araistrick** [comment]
Thanks for raising this, I thought all were working but I will test and fix asap. Should be fixed by tommorow or day after, I will send you a special GitHub branch to use

**Comment by araistrick** [comment]
I fixed an issue with the tiger IKs and verified that animation_mode='run' is at least funcitonal (if not the the most realistic, Id love to revisit / improve this later). Let me know what if any specific issues still persist
