### ISSUE TITLE
Why so hard to make a video ? Only a waste of time !

### ISSUE THREAD

**Issue by jiarenyf** [princeton-vl/infinigen#95]
Always many error with unknown case, spent 4 days and cannot  generate a video through these useless introduction ...

<img width="360" alt="image" src="https://github.com/princeton-vl/infinigen/assets/12405578/ff934ba1-ce91-4b0c-bd90-88badd261029">

Errors without reason, only with 'unknown case' in the log file ...'

A waste of 4 days ...

**Comment by araistrick** [comment]
Hello, please share the underlying logs from within your outputs/JOBNAME/SEED/logs folder and we should be able to quickly determine what is going wrong.

The unknown cause only means that the manager program doesn't know how it summarize the error, but you can still view the underlying logs. I will clarify the error message for this.
