### ISSUE TITLE
in blender only saw the placeholder not mesh

### ISSUE THREAD

**Issue by chongxian** [princeton-vl/infinigen#97]
![image](https://github.com/princeton-vl/infinigen/assets/18145013/6a0b52c8-8ef1-4737-837f-7bf522f25963)
hello, I open the scene.blend only saw the box(placeholder) but never saw the mesh, if I click Render button can get the image. However, I want to saw the mesh in the blender viewport, how can I do to unhide them.
And I follow other issue to do,but also can't solve this problem, Thanks for your help.
![image](https://github.com/princeton-vl/infinigen/assets/18145013/a4222a68-59d2-49a5-9e62-0fb99569217c)

**Comment by araistrick** [comment]
See #94
